// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: balance.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesRequest) Reset() {
	*x = GetBalancesRequest{}
	mi := &file_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesRequest) ProtoMessage() {}

func (x *GetBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetBalancesRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalancesRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

type GetBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*UserBalance         `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	Debts         []*Debt                `protobuf:"bytes,2,rep,name=debts,proto3" json:"debts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesResponse) Reset() {
	*x = GetBalancesResponse{}
	mi := &file_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesResponse) ProtoMessage() {}

func (x *GetBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetBalancesResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalancesResponse) GetBalances() []*UserBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *GetBalancesResponse) GetDebts() []*Debt {
	if x != nil {
		return x.Debts
	}
	return nil
}

type UserBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNom       string                 `protobuf:"bytes,2,opt,name=user_nom,json=userNom,proto3" json:"user_nom,omitempty"`
	UserPrenom    string                 `protobuf:"bytes,3,opt,name=user_prenom,json=userPrenom,proto3" json:"user_prenom,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	TotalPaid     float64                `protobuf:"fixed64,5,opt,name=total_paid,json=totalPaid,proto3" json:"total_paid,omitempty"`    // Total amount paid by user
	TotalOwed     float64                `protobuf:"fixed64,6,opt,name=total_owed,json=totalOwed,proto3" json:"total_owed,omitempty"`    // Total amount user owes
	NetBalance    float64                `protobuf:"fixed64,7,opt,name=net_balance,json=netBalance,proto3" json:"net_balance,omitempty"` // Positive = others owe them, Negative = they owe others
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBalance) Reset() {
	*x = UserBalance{}
	mi := &file_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBalance) ProtoMessage() {}

func (x *UserBalance) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBalance.ProtoReflect.Descriptor instead.
func (*UserBalance) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{2}
}

func (x *UserBalance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserBalance) GetUserNom() string {
	if x != nil {
		return x.UserNom
	}
	return ""
}

func (x *UserBalance) GetUserPrenom() string {
	if x != nil {
		return x.UserPrenom
	}
	return ""
}

func (x *UserBalance) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UserBalance) GetTotalPaid() float64 {
	if x != nil {
		return x.TotalPaid
	}
	return 0
}

func (x *UserBalance) GetTotalOwed() float64 {
	if x != nil {
		return x.TotalOwed
	}
	return 0
}

func (x *UserBalance) GetNetBalance() float64 {
	if x != nil {
		return x.NetBalance
	}
	return 0
}

type Debt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromUserId     string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromUserNom    string                 `protobuf:"bytes,2,opt,name=from_user_nom,json=fromUserNom,proto3" json:"from_user_nom,omitempty"`
	FromUserPrenom string                 `protobuf:"bytes,3,opt,name=from_user_prenom,json=fromUserPrenom,proto3" json:"from_user_prenom,omitempty"`
	ToUserId       string                 `protobuf:"bytes,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	ToUserNom      string                 `protobuf:"bytes,5,opt,name=to_user_nom,json=toUserNom,proto3" json:"to_user_nom,omitempty"`
	ToUserPrenom   string                 `protobuf:"bytes,6,opt,name=to_user_prenom,json=toUserPrenom,proto3" json:"to_user_prenom,omitempty"`
	Amount         float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Debt) Reset() {
	*x = Debt{}
	mi := &file_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Debt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debt) ProtoMessage() {}

func (x *Debt) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debt.ProtoReflect.Descriptor instead.
func (*Debt) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{3}
}

func (x *Debt) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *Debt) GetFromUserNom() string {
	if x != nil {
		return x.FromUserNom
	}
	return ""
}

func (x *Debt) GetFromUserPrenom() string {
	if x != nil {
		return x.FromUserPrenom
	}
	return ""
}

func (x *Debt) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *Debt) GetToUserNom() string {
	if x != nil {
		return x.ToUserNom
	}
	return ""
}

func (x *Debt) GetToUserPrenom() string {
	if x != nil {
		return x.ToUserPrenom
	}
	return ""
}

func (x *Debt) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetSimplifiedDebtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimplifiedDebtsRequest) Reset() {
	*x = GetSimplifiedDebtsRequest{}
	mi := &file_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimplifiedDebtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimplifiedDebtsRequest) ProtoMessage() {}

func (x *GetSimplifiedDebtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimplifiedDebtsRequest.ProtoReflect.Descriptor instead.
func (*GetSimplifiedDebtsRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{4}
}

func (x *GetSimplifiedDebtsRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

type GetSimplifiedDebtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Debts         []*SimplifiedDebt      `protobuf:"bytes,1,rep,name=debts,proto3" json:"debts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimplifiedDebtsResponse) Reset() {
	*x = GetSimplifiedDebtsResponse{}
	mi := &file_balance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimplifiedDebtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimplifiedDebtsResponse) ProtoMessage() {}

func (x *GetSimplifiedDebtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimplifiedDebtsResponse.ProtoReflect.Descriptor instead.
func (*GetSimplifiedDebtsResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{5}
}

func (x *GetSimplifiedDebtsResponse) GetDebts() []*SimplifiedDebt {
	if x != nil {
		return x.Debts
	}
	return nil
}

type SimplifiedDebt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromUserId     string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromUserNom    string                 `protobuf:"bytes,2,opt,name=from_user_nom,json=fromUserNom,proto3" json:"from_user_nom,omitempty"`
	FromUserPrenom string                 `protobuf:"bytes,3,opt,name=from_user_prenom,json=fromUserPrenom,proto3" json:"from_user_prenom,omitempty"`
	FromAvatarUrl  *string                `protobuf:"bytes,4,opt,name=from_avatar_url,json=fromAvatarUrl,proto3,oneof" json:"from_avatar_url,omitempty"`
	ToUserId       string                 `protobuf:"bytes,5,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	ToUserNom      string                 `protobuf:"bytes,6,opt,name=to_user_nom,json=toUserNom,proto3" json:"to_user_nom,omitempty"`
	ToUserPrenom   string                 `protobuf:"bytes,7,opt,name=to_user_prenom,json=toUserPrenom,proto3" json:"to_user_prenom,omitempty"`
	ToAvatarUrl    *string                `protobuf:"bytes,8,opt,name=to_avatar_url,json=toAvatarUrl,proto3,oneof" json:"to_avatar_url,omitempty"`
	Amount         float64                `protobuf:"fixed64,9,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimplifiedDebt) Reset() {
	*x = SimplifiedDebt{}
	mi := &file_balance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimplifiedDebt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplifiedDebt) ProtoMessage() {}

func (x *SimplifiedDebt) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplifiedDebt.ProtoReflect.Descriptor instead.
func (*SimplifiedDebt) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{6}
}

func (x *SimplifiedDebt) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *SimplifiedDebt) GetFromUserNom() string {
	if x != nil {
		return x.FromUserNom
	}
	return ""
}

func (x *SimplifiedDebt) GetFromUserPrenom() string {
	if x != nil {
		return x.FromUserPrenom
	}
	return ""
}

func (x *SimplifiedDebt) GetFromAvatarUrl() string {
	if x != nil && x.FromAvatarUrl != nil {
		return *x.FromAvatarUrl
	}
	return ""
}

func (x *SimplifiedDebt) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *SimplifiedDebt) GetToUserNom() string {
	if x != nil {
		return x.ToUserNom
	}
	return ""
}

func (x *SimplifiedDebt) GetToUserPrenom() string {
	if x != nil {
		return x.ToUserPrenom
	}
	return ""
}

func (x *SimplifiedDebt) GetToAvatarUrl() string {
	if x != nil && x.ToAvatarUrl != nil {
		return *x.ToAvatarUrl
	}
	return ""
}

func (x *SimplifiedDebt) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetBalanceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	StartDate     *string                `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *string                `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceHistoryRequest) Reset() {
	*x = GetBalanceHistoryRequest{}
	mi := &file_balance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceHistoryRequest) ProtoMessage() {}

func (x *GetBalanceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalanceHistoryRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetBalanceHistoryRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *GetBalanceHistoryRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

type GetBalanceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*BalanceHistoryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceHistoryResponse) Reset() {
	*x = GetBalanceHistoryResponse{}
	mi := &file_balance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceHistoryResponse) ProtoMessage() {}

func (x *GetBalanceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalanceHistoryResponse) GetEntries() []*BalanceHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BalanceHistoryEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Date              string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	CumulativeBalance float64                `protobuf:"fixed64,2,opt,name=cumulative_balance,json=cumulativeBalance,proto3" json:"cumulative_balance,omitempty"`
	EventType         string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "expense" or "payment"
	EventId           string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Description       string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Amount            float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BalanceHistoryEntry) Reset() {
	*x = BalanceHistoryEntry{}
	mi := &file_balance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceHistoryEntry) ProtoMessage() {}

func (x *BalanceHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceHistoryEntry.ProtoReflect.Descriptor instead.
func (*BalanceHistoryEntry) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{9}
}

func (x *BalanceHistoryEntry) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *BalanceHistoryEntry) GetCumulativeBalance() float64 {
	if x != nil {
		return x.CumulativeBalance
	}
	return 0
}

func (x *BalanceHistoryEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BalanceHistoryEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BalanceHistoryEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BalanceHistoryEntry) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_balance_proto protoreflect.FileDescriptor

const file_balance_proto_rawDesc = "" +
	"\n" +
	"\rbalance.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\"9\n" +
	"\x12GetBalancesRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\"h\n" +
	"\x13GetBalancesResponse\x12.\n" +
	"\bbalances\x18\x01 \x03(\v2\x12.coloc.UserBalanceR\bbalances\x12!\n" +
	"\x05debts\x18\x02 \x03(\v2\v.coloc.DebtR\x05debts\"\xf4\x01\n" +
	"\vUserBalance\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_nom\x18\x02 \x01(\tR\auserNom\x12\x1f\n" +
	"\vuser_prenom\x18\x03 \x01(\tR\n" +
	"userPrenom\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"total_paid\x18\x05 \x01(\x01R\ttotalPaid\x12\x1d\n" +
	"\n" +
	"total_owed\x18\x06 \x01(\x01R\ttotalOwed\x12\x1f\n" +
	"\vnet_balance\x18\a \x01(\x01R\n" +
	"netBalanceB\r\n" +
	"\v_avatar_url\"\xf2\x01\n" +
	"\x04Debt\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\"\n" +
	"\rfrom_user_nom\x18\x02 \x01(\tR\vfromUserNom\x12(\n" +
	"\x10from_user_prenom\x18\x03 \x01(\tR\x0efromUserPrenom\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\tR\btoUserId\x12\x1e\n" +
	"\vto_user_nom\x18\x05 \x01(\tR\ttoUserNom\x12$\n" +
	"\x0eto_user_prenom\x18\x06 \x01(\tR\ftoUserPrenom\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\"@\n" +
	"\x19GetSimplifiedDebtsRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\"I\n" +
	"\x1aGetSimplifiedDebtsResponse\x12+\n" +
	"\x05debts\x18\x01 \x03(\v2\x15.coloc.SimplifiedDebtR\x05debts\"\xf8\x02\n" +
	"\x0eSimplifiedDebt\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\"\n" +
	"\rfrom_user_nom\x18\x02 \x01(\tR\vfromUserNom\x12(\n" +
	"\x10from_user_prenom\x18\x03 \x01(\tR\x0efromUserPrenom\x12+\n" +
	"\x0ffrom_avatar_url\x18\x04 \x01(\tH\x00R\rfromAvatarUrl\x88\x01\x01\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x05 \x01(\tR\btoUserId\x12\x1e\n" +
	"\vto_user_nom\x18\x06 \x01(\tR\ttoUserNom\x12$\n" +
	"\x0eto_user_prenom\x18\a \x01(\tR\ftoUserPrenom\x12'\n" +
	"\rto_avatar_url\x18\b \x01(\tH\x01R\vtoAvatarUrl\x88\x01\x01\x12\x16\n" +
	"\x06amount\x18\t \x01(\x01R\x06amountB\x12\n" +
	"\x10_from_avatar_urlB\x10\n" +
	"\x0e_to_avatar_url\"\x9f\x01\n" +
	"\x18GetBalanceHistoryRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\"\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tH\x00R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x03 \x01(\tH\x01R\aendDate\x88\x01\x01B\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_date\"Q\n" +
	"\x19GetBalanceHistoryResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.coloc.BalanceHistoryEntryR\aentries\"\xcc\x01\n" +
	"\x13BalanceHistoryEntry\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12-\n" +
	"\x12cumulative_balance\x18\x02 \x01(\x01R\x11cumulativeBalance\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount2\xb7\x03\n" +
	"\x0eBalanceService\x12w\n" +
	"\vGetBalances\x12\x19.coloc.GetBalancesRequest\x1a\x1a.coloc.GetBalancesResponse\"1\x82\xd3\xe4\x93\x02+\x12)/api/colocations/{colocation_id}/balances\x12\x97\x01\n" +
	"\x12GetSimplifiedDebts\x12 .coloc.GetSimplifiedDebtsRequest\x1a!.coloc.GetSimplifiedDebtsResponse\"<\x82\xd3\xe4\x93\x026\x124/api/colocations/{colocation_id}/balances/simplified\x12\x91\x01\n" +
	"\x11GetBalanceHistory\x12\x1f.coloc.GetBalanceHistoryRequest\x1a .coloc.GetBalanceHistoryResponse\"9\x82\xd3\xe4\x93\x023\x121/api/colocations/{colocation_id}/balances/historyB,Z*github.com/vblanchet22/back_coloc/proto/pbb\x06proto3"

var (
	file_balance_proto_rawDescOnce sync.Once
	file_balance_proto_rawDescData []byte
)

func file_balance_proto_rawDescGZIP() []byte {
	file_balance_proto_rawDescOnce.Do(func() {
		file_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)))
	})
	return file_balance_proto_rawDescData
}

var file_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_balance_proto_goTypes = []any{
	(*GetBalancesRequest)(nil),         // 0: coloc.GetBalancesRequest
	(*GetBalancesResponse)(nil),        // 1: coloc.GetBalancesResponse
	(*UserBalance)(nil),                // 2: coloc.UserBalance
	(*Debt)(nil),                       // 3: coloc.Debt
	(*GetSimplifiedDebtsRequest)(nil),  // 4: coloc.GetSimplifiedDebtsRequest
	(*GetSimplifiedDebtsResponse)(nil), // 5: coloc.GetSimplifiedDebtsResponse
	(*SimplifiedDebt)(nil),             // 6: coloc.SimplifiedDebt
	(*GetBalanceHistoryRequest)(nil),   // 7: coloc.GetBalanceHistoryRequest
	(*GetBalanceHistoryResponse)(nil),  // 8: coloc.GetBalanceHistoryResponse
	(*BalanceHistoryEntry)(nil),        // 9: coloc.BalanceHistoryEntry
}
var file_balance_proto_depIdxs = []int32{
	2, // 0: coloc.GetBalancesResponse.balances:type_name -> coloc.UserBalance
	3, // 1: coloc.GetBalancesResponse.debts:type_name -> coloc.Debt
	6, // 2: coloc.GetSimplifiedDebtsResponse.debts:type_name -> coloc.SimplifiedDebt
	9, // 3: coloc.GetBalanceHistoryResponse.entries:type_name -> coloc.BalanceHistoryEntry
	0, // 4: coloc.BalanceService.GetBalances:input_type -> coloc.GetBalancesRequest
	4, // 5: coloc.BalanceService.GetSimplifiedDebts:input_type -> coloc.GetSimplifiedDebtsRequest
	7, // 6: coloc.BalanceService.GetBalanceHistory:input_type -> coloc.GetBalanceHistoryRequest
	1, // 7: coloc.BalanceService.GetBalances:output_type -> coloc.GetBalancesResponse
	5, // 8: coloc.BalanceService.GetSimplifiedDebts:output_type -> coloc.GetSimplifiedDebtsResponse
	8, // 9: coloc.BalanceService.GetBalanceHistory:output_type -> coloc.GetBalanceHistoryResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_balance_proto_init() }
func file_balance_proto_init() {
	if File_balance_proto != nil {
		return
	}
	file_balance_proto_msgTypes[2].OneofWrappers = []any{}
	file_balance_proto_msgTypes[6].OneofWrappers = []any{}
	file_balance_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_proto_goTypes,
		DependencyIndexes: file_balance_proto_depIdxs,
		MessageInfos:      file_balance_proto_msgTypes,
	}.Build()
	File_balance_proto = out.File
	file_balance_proto_goTypes = nil
	file_balance_proto_depIdxs = nil
}
