// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: category.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{0}
}

func (x *ListCategoriesRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{1}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          *string                `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Color         *string                `protobuf:"bytes,4,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCategoryRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *CreateCategoryRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Icon          *string                `protobuf:"bytes,4,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Color         *string                `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCategoryRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *UpdateCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *UpdateCategoryRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_category_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCategoryRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *DeleteCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_category_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCategoryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	StartDate     *string                `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"` // Format: YYYY-MM-DD
	EndDate       *string                `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`       // Format: YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryStatsRequest) Reset() {
	*x = GetCategoryStatsRequest{}
	mi := &file_category_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryStatsRequest) ProtoMessage() {}

func (x *GetCategoryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryStatsRequest) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{6}
}

func (x *GetCategoryStatsRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetCategoryStatsRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *GetCategoryStatsRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

type GetCategoryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*CategoryStat        `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryStatsResponse) Reset() {
	*x = GetCategoryStatsResponse{}
	mi := &file_category_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryStatsResponse) ProtoMessage() {}

func (x *GetCategoryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryStatsResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryStatsResponse) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{7}
}

func (x *GetCategoryStatsResponse) GetStats() []*CategoryStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetCategoryStatsResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          *string                `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Color         *string                `protobuf:"bytes,4,opt,name=color,proto3,oneof" json:"color,omitempty"`
	IsGlobal      bool                   `protobuf:"varint,5,opt,name=is_global,json=isGlobal,proto3" json:"is_global,omitempty"` // true if global category, false if custom
	ColocationId  *string                `protobuf:"bytes,6,opt,name=colocation_id,json=colocationId,proto3,oneof" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_category_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{8}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *Category) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *Category) GetIsGlobal() bool {
	if x != nil {
		return x.IsGlobal
	}
	return false
}

func (x *Category) GetColocationId() string {
	if x != nil && x.ColocationId != nil {
		return *x.ColocationId
	}
	return ""
}

type CategoryStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Icon          *string                `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Color         *string                `protobuf:"bytes,4,opt,name=color,proto3,oneof" json:"color,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	ExpenseCount  int32                  `protobuf:"varint,6,opt,name=expense_count,json=expenseCount,proto3" json:"expense_count,omitempty"`
	Percentage    float64                `protobuf:"fixed64,7,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStat) Reset() {
	*x = CategoryStat{}
	mi := &file_category_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStat) ProtoMessage() {}

func (x *CategoryStat) ProtoReflect() protoreflect.Message {
	mi := &file_category_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStat.ProtoReflect.Descriptor instead.
func (*CategoryStat) Descriptor() ([]byte, []int) {
	return file_category_proto_rawDescGZIP(), []int{9}
}

func (x *CategoryStat) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryStat) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryStat) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *CategoryStat) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *CategoryStat) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CategoryStat) GetExpenseCount() int32 {
	if x != nil {
		return x.ExpenseCount
	}
	return 0
}

func (x *CategoryStat) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

var File_category_proto protoreflect.FileDescriptor

const file_category_proto_rawDesc = "" +
	"\n" +
	"\x0ecategory.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\"<\n" +
	"\x15ListCategoriesRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\"I\n" +
	"\x16ListCategoriesResponse\x12/\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x0f.coloc.CategoryR\n" +
	"categories\"\x97\x01\n" +
	"\x15CreateCategoryRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\x04icon\x18\x03 \x01(\tH\x00R\x04icon\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x04 \x01(\tH\x01R\x05color\x88\x01\x01B\a\n" +
	"\x05_iconB\b\n" +
	"\x06_color\"\xb5\x01\n" +
	"\x15UpdateCategoryRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x04 \x01(\tH\x01R\x04icon\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x02R\x05color\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_iconB\b\n" +
	"\x06_color\"L\n" +
	"\x15DeleteCategoryRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"2\n" +
	"\x16DeleteCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9e\x01\n" +
	"\x17GetCategoryStatsRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\"\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tH\x00R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x03 \x01(\tH\x01R\aendDate\x88\x01\x01B\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_date\"h\n" +
	"\x18GetCategoryStatsResponse\x12)\n" +
	"\x05stats\x18\x01 \x03(\v2\x13.coloc.CategoryStatR\x05stats\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\"\xce\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\x04icon\x18\x03 \x01(\tH\x00R\x04icon\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x04 \x01(\tH\x01R\x05color\x88\x01\x01\x12\x1b\n" +
	"\tis_global\x18\x05 \x01(\bR\bisGlobal\x12(\n" +
	"\rcolocation_id\x18\x06 \x01(\tH\x02R\fcolocationId\x88\x01\x01B\a\n" +
	"\x05_iconB\b\n" +
	"\x06_colorB\x10\n" +
	"\x0e_colocation_id\"\x83\x02\n" +
	"\fCategoryStat\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x17\n" +
	"\x04icon\x18\x03 \x01(\tH\x00R\x04icon\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x04 \x01(\tH\x01R\x05color\x88\x01\x01\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12#\n" +
	"\rexpense_count\x18\x06 \x01(\x05R\fexpenseCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\a \x01(\x01R\n" +
	"percentageB\a\n" +
	"\x05_iconB\b\n" +
	"\x06_color2\xa8\x05\n" +
	"\x0fCategoryService\x12\x82\x01\n" +
	"\x0eListCategories\x12\x1c.coloc.ListCategoriesRequest\x1a\x1d.coloc.ListCategoriesResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/colocations/{colocation_id}/categories\x12w\n" +
	"\x0eCreateCategory\x12\x1c.coloc.CreateCategoryRequest\x1a\x0f.coloc.Category\"6\x82\xd3\xe4\x93\x020:\x01*\"+/api/colocations/{colocation_id}/categories\x12|\n" +
	"\x0eUpdateCategory\x12\x1c.coloc.UpdateCategoryRequest\x1a\x0f.coloc.Category\";\x82\xd3\xe4\x93\x025:\x01*\x1a0/api/colocations/{colocation_id}/categories/{id}\x12\x87\x01\n" +
	"\x0eDeleteCategory\x12\x1c.coloc.DeleteCategoryRequest\x1a\x1d.coloc.DeleteCategoryResponse\"8\x82\xd3\xe4\x93\x022*0/api/colocations/{colocation_id}/categories/{id}\x12\x8e\x01\n" +
	"\x10GetCategoryStats\x12\x1e.coloc.GetCategoryStatsRequest\x1a\x1f.coloc.GetCategoryStatsResponse\"9\x82\xd3\xe4\x93\x023\x121/api/colocations/{colocation_id}/categories/statsB,Z*github.com/vblanchet22/back_coloc/proto/pbb\x06proto3"

var (
	file_category_proto_rawDescOnce sync.Once
	file_category_proto_rawDescData []byte
)

func file_category_proto_rawDescGZIP() []byte {
	file_category_proto_rawDescOnce.Do(func() {
		file_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_proto_rawDesc), len(file_category_proto_rawDesc)))
	})
	return file_category_proto_rawDescData
}

var file_category_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_category_proto_goTypes = []any{
	(*ListCategoriesRequest)(nil),    // 0: coloc.ListCategoriesRequest
	(*ListCategoriesResponse)(nil),   // 1: coloc.ListCategoriesResponse
	(*CreateCategoryRequest)(nil),    // 2: coloc.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),    // 3: coloc.UpdateCategoryRequest
	(*DeleteCategoryRequest)(nil),    // 4: coloc.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil),   // 5: coloc.DeleteCategoryResponse
	(*GetCategoryStatsRequest)(nil),  // 6: coloc.GetCategoryStatsRequest
	(*GetCategoryStatsResponse)(nil), // 7: coloc.GetCategoryStatsResponse
	(*Category)(nil),                 // 8: coloc.Category
	(*CategoryStat)(nil),             // 9: coloc.CategoryStat
}
var file_category_proto_depIdxs = []int32{
	8, // 0: coloc.ListCategoriesResponse.categories:type_name -> coloc.Category
	9, // 1: coloc.GetCategoryStatsResponse.stats:type_name -> coloc.CategoryStat
	0, // 2: coloc.CategoryService.ListCategories:input_type -> coloc.ListCategoriesRequest
	2, // 3: coloc.CategoryService.CreateCategory:input_type -> coloc.CreateCategoryRequest
	3, // 4: coloc.CategoryService.UpdateCategory:input_type -> coloc.UpdateCategoryRequest
	4, // 5: coloc.CategoryService.DeleteCategory:input_type -> coloc.DeleteCategoryRequest
	6, // 6: coloc.CategoryService.GetCategoryStats:input_type -> coloc.GetCategoryStatsRequest
	1, // 7: coloc.CategoryService.ListCategories:output_type -> coloc.ListCategoriesResponse
	8, // 8: coloc.CategoryService.CreateCategory:output_type -> coloc.Category
	8, // 9: coloc.CategoryService.UpdateCategory:output_type -> coloc.Category
	5, // 10: coloc.CategoryService.DeleteCategory:output_type -> coloc.DeleteCategoryResponse
	7, // 11: coloc.CategoryService.GetCategoryStats:output_type -> coloc.GetCategoryStatsResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_category_proto_init() }
func file_category_proto_init() {
	if File_category_proto != nil {
		return
	}
	file_category_proto_msgTypes[2].OneofWrappers = []any{}
	file_category_proto_msgTypes[3].OneofWrappers = []any{}
	file_category_proto_msgTypes[6].OneofWrappers = []any{}
	file_category_proto_msgTypes[8].OneofWrappers = []any{}
	file_category_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_proto_rawDesc), len(file_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_proto_goTypes,
		DependencyIndexes: file_category_proto_depIdxs,
		MessageInfos:      file_category_proto_msgTypes,
	}.Build()
	File_category_proto = out.File
	file_category_proto_goTypes = nil
	file_category_proto_depIdxs = nil
}
