// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: colocation.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberRole int32

const (
	MemberRole_MEMBER_ROLE_UNSPECIFIED MemberRole = 0
	MemberRole_MEMBER_ROLE_MEMBER      MemberRole = 1
	MemberRole_MEMBER_ROLE_ADMIN       MemberRole = 2
)

// Enum value maps for MemberRole.
var (
	MemberRole_name = map[int32]string{
		0: "MEMBER_ROLE_UNSPECIFIED",
		1: "MEMBER_ROLE_MEMBER",
		2: "MEMBER_ROLE_ADMIN",
	}
	MemberRole_value = map[string]int32{
		"MEMBER_ROLE_UNSPECIFIED": 0,
		"MEMBER_ROLE_MEMBER":      1,
		"MEMBER_ROLE_ADMIN":       2,
	}
)

func (x MemberRole) Enum() *MemberRole {
	p := new(MemberRole)
	*p = x
	return p
}

func (x MemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_colocation_proto_enumTypes[0].Descriptor()
}

func (MemberRole) Type() protoreflect.EnumType {
	return &file_colocation_proto_enumTypes[0]
}

func (x MemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberRole.Descriptor instead.
func (MemberRole) EnumDescriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{0}
}

type InvitationStatus int32

const (
	InvitationStatus_INVITATION_STATUS_UNSPECIFIED InvitationStatus = 0
	InvitationStatus_INVITATION_STATUS_PENDING     InvitationStatus = 1
	InvitationStatus_INVITATION_STATUS_ACCEPTED    InvitationStatus = 2
	InvitationStatus_INVITATION_STATUS_REJECTED    InvitationStatus = 3
	InvitationStatus_INVITATION_STATUS_EXPIRED     InvitationStatus = 4
)

// Enum value maps for InvitationStatus.
var (
	InvitationStatus_name = map[int32]string{
		0: "INVITATION_STATUS_UNSPECIFIED",
		1: "INVITATION_STATUS_PENDING",
		2: "INVITATION_STATUS_ACCEPTED",
		3: "INVITATION_STATUS_REJECTED",
		4: "INVITATION_STATUS_EXPIRED",
	}
	InvitationStatus_value = map[string]int32{
		"INVITATION_STATUS_UNSPECIFIED": 0,
		"INVITATION_STATUS_PENDING":     1,
		"INVITATION_STATUS_ACCEPTED":    2,
		"INVITATION_STATUS_REJECTED":    3,
		"INVITATION_STATUS_EXPIRED":     4,
	}
)

func (x InvitationStatus) Enum() *InvitationStatus {
	p := new(InvitationStatus)
	*p = x
	return p
}

func (x InvitationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvitationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_colocation_proto_enumTypes[1].Descriptor()
}

func (InvitationStatus) Type() protoreflect.EnumType {
	return &file_colocation_proto_enumTypes[1]
}

func (x InvitationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvitationStatus.Descriptor instead.
func (InvitationStatus) EnumDescriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{1}
}

type CreateColocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Address       *string                `protobuf:"bytes,3,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColocationRequest) Reset() {
	*x = CreateColocationRequest{}
	mi := &file_colocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColocationRequest) ProtoMessage() {}

func (x *CreateColocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColocationRequest.ProtoReflect.Descriptor instead.
func (*CreateColocationRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateColocationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateColocationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateColocationRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

type GetColocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetColocationRequest) Reset() {
	*x = GetColocationRequest{}
	mi := &file_colocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetColocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetColocationRequest) ProtoMessage() {}

func (x *GetColocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetColocationRequest.ProtoReflect.Descriptor instead.
func (*GetColocationRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{1}
}

func (x *GetColocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListColocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListColocationsRequest) Reset() {
	*x = ListColocationsRequest{}
	mi := &file_colocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListColocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListColocationsRequest) ProtoMessage() {}

func (x *ListColocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListColocationsRequest.ProtoReflect.Descriptor instead.
func (*ListColocationsRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{2}
}

type ListColocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Colocations   []*Colocation          `protobuf:"bytes,1,rep,name=colocations,proto3" json:"colocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListColocationsResponse) Reset() {
	*x = ListColocationsResponse{}
	mi := &file_colocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListColocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListColocationsResponse) ProtoMessage() {}

func (x *ListColocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListColocationsResponse.ProtoReflect.Descriptor instead.
func (*ListColocationsResponse) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{3}
}

func (x *ListColocationsResponse) GetColocations() []*Colocation {
	if x != nil {
		return x.Colocations
	}
	return nil
}

type UpdateColocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Address       *string                `protobuf:"bytes,4,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateColocationRequest) Reset() {
	*x = UpdateColocationRequest{}
	mi := &file_colocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateColocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColocationRequest) ProtoMessage() {}

func (x *UpdateColocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateColocationRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateColocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateColocationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateColocationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateColocationRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

type DeleteColocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteColocationRequest) Reset() {
	*x = DeleteColocationRequest{}
	mi := &file_colocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteColocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteColocationRequest) ProtoMessage() {}

func (x *DeleteColocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteColocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteColocationRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteColocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteColocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteColocationResponse) Reset() {
	*x = DeleteColocationResponse{}
	mi := &file_colocation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteColocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteColocationResponse) ProtoMessage() {}

func (x *DeleteColocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteColocationResponse.ProtoReflect.Descriptor instead.
func (*DeleteColocationResponse) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteColocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type JoinColocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinColocationRequest) Reset() {
	*x = JoinColocationRequest{}
	mi := &file_colocation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinColocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinColocationRequest) ProtoMessage() {}

func (x *JoinColocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinColocationRequest.ProtoReflect.Descriptor instead.
func (*JoinColocationRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{7}
}

func (x *JoinColocationRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type LeaveColocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveColocationRequest) Reset() {
	*x = LeaveColocationRequest{}
	mi := &file_colocation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveColocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveColocationRequest) ProtoMessage() {}

func (x *LeaveColocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveColocationRequest.ProtoReflect.Descriptor instead.
func (*LeaveColocationRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveColocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LeaveColocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveColocationResponse) Reset() {
	*x = LeaveColocationResponse{}
	mi := &file_colocation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveColocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveColocationResponse) ProtoMessage() {}

func (x *LeaveColocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveColocationResponse.ProtoReflect.Descriptor instead.
func (*LeaveColocationResponse) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveColocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersRequest) Reset() {
	*x = GetMembersRequest{}
	mi := &file_colocation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersRequest) ProtoMessage() {}

func (x *GetMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersRequest.ProtoReflect.Descriptor instead.
func (*GetMembersRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{10}
}

func (x *GetMembersRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

type GetMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*ColocationMember    `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembersResponse) Reset() {
	*x = GetMembersResponse{}
	mi := &file_colocation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembersResponse) ProtoMessage() {}

func (x *GetMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembersResponse.ProtoReflect.Descriptor instead.
func (*GetMembersResponse) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{11}
}

func (x *GetMembersResponse) GetMembers() []*ColocationMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_colocation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveMemberRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_colocation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          MemberRole             `protobuf:"varint,3,opt,name=role,proto3,enum=coloc.MemberRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_colocation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateMemberRoleRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

type RegenerateInviteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateInviteCodeRequest) Reset() {
	*x = RegenerateInviteCodeRequest{}
	mi := &file_colocation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateInviteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateInviteCodeRequest) ProtoMessage() {}

func (x *RegenerateInviteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateInviteCodeRequest.ProtoReflect.Descriptor instead.
func (*RegenerateInviteCodeRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{15}
}

func (x *RegenerateInviteCodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegenerateInviteCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteCode    string                 `protobuf:"bytes,1,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateInviteCodeResponse) Reset() {
	*x = RegenerateInviteCodeResponse{}
	mi := &file_colocation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateInviteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateInviteCodeResponse) ProtoMessage() {}

func (x *RegenerateInviteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateInviteCodeResponse.ProtoReflect.Descriptor instead.
func (*RegenerateInviteCodeResponse) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{16}
}

func (x *RegenerateInviteCodeResponse) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

type SendInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInvitationRequest) Reset() {
	*x = SendInvitationRequest{}
	mi := &file_colocation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInvitationRequest) ProtoMessage() {}

func (x *SendInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInvitationRequest.ProtoReflect.Descriptor instead.
func (*SendInvitationRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{17}
}

func (x *SendInvitationRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *SendInvitationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_colocation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{18}
}

func (x *ListInvitationsRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

type ListInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsResponse) Reset() {
	*x = ListInvitationsResponse{}
	mi := &file_colocation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsResponse) ProtoMessage() {}

func (x *ListInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{19}
}

func (x *ListInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

type CancelInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	InvitationId  string                 `protobuf:"bytes,2,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInvitationRequest) Reset() {
	*x = CancelInvitationRequest{}
	mi := &file_colocation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInvitationRequest) ProtoMessage() {}

func (x *CancelInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInvitationRequest.ProtoReflect.Descriptor instead.
func (*CancelInvitationRequest) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{20}
}

func (x *CancelInvitationRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CancelInvitationRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type CancelInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInvitationResponse) Reset() {
	*x = CancelInvitationResponse{}
	mi := &file_colocation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInvitationResponse) ProtoMessage() {}

func (x *CancelInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInvitationResponse.ProtoReflect.Descriptor instead.
func (*CancelInvitationResponse) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{21}
}

func (x *CancelInvitationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Colocation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Address         *string                `protobuf:"bytes,4,opt,name=address,proto3,oneof" json:"address,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	InviteCode      string                 `protobuf:"bytes,6,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CurrentUserRole MemberRole             `protobuf:"varint,9,opt,name=current_user_role,json=currentUserRole,proto3,enum=coloc.MemberRole" json:"current_user_role,omitempty"`
	MemberCount     int32                  `protobuf:"varint,10,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Colocation) Reset() {
	*x = Colocation{}
	mi := &file_colocation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Colocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Colocation) ProtoMessage() {}

func (x *Colocation) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Colocation.ProtoReflect.Descriptor instead.
func (*Colocation) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{22}
}

func (x *Colocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Colocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Colocation) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Colocation) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Colocation) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Colocation) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *Colocation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Colocation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Colocation) GetCurrentUserRole() MemberRole {
	if x != nil {
		return x.CurrentUserRole
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

func (x *Colocation) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type ColocationMember struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ColocationId string                 `protobuf:"bytes,3,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Role         MemberRole             `protobuf:"varint,4,opt,name=role,proto3,enum=coloc.MemberRole" json:"role,omitempty"`
	JoinedAt     string                 `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	// User details
	Email         string  `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Nom           string  `protobuf:"bytes,7,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom        string  `protobuf:"bytes,8,opt,name=prenom,proto3" json:"prenom,omitempty"`
	AvatarUrl     *string `protobuf:"bytes,9,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColocationMember) Reset() {
	*x = ColocationMember{}
	mi := &file_colocation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColocationMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColocationMember) ProtoMessage() {}

func (x *ColocationMember) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColocationMember.ProtoReflect.Descriptor instead.
func (*ColocationMember) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{23}
}

func (x *ColocationMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ColocationMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ColocationMember) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *ColocationMember) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

func (x *ColocationMember) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *ColocationMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ColocationMember) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *ColocationMember) GetPrenom() string {
	if x != nil {
		return x.Prenom
	}
	return ""
}

func (x *ColocationMember) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

type Invitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ColocationId  string                 `protobuf:"bytes,2,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	InvitedBy     string                 `protobuf:"bytes,3,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	InvitedEmail  string                 `protobuf:"bytes,4,opt,name=invited_email,json=invitedEmail,proto3" json:"invited_email,omitempty"`
	Status        InvitationStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=coloc.InvitationStatus" json:"status,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_colocation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_colocation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_colocation_proto_rawDescGZIP(), []int{24}
}

func (x *Invitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invitation) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *Invitation) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *Invitation) GetInvitedEmail() string {
	if x != nil {
		return x.InvitedEmail
	}
	return ""
}

func (x *Invitation) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_INVITATION_STATUS_UNSPECIFIED
}

func (x *Invitation) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Invitation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_colocation_proto protoreflect.FileDescriptor

const file_colocation_proto_rawDesc = "" +
	"\n" +
	"\x10colocation.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\"\x8f\x01\n" +
	"\x17CreateColocationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x03 \x01(\tH\x01R\aaddress\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_address\"&\n" +
	"\x14GetColocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16ListColocationsRequest\"N\n" +
	"\x17ListColocationsResponse\x123\n" +
	"\vcolocations\x18\x01 \x03(\v2\x11.coloc.ColocationR\vcolocations\"\xad\x01\n" +
	"\x17UpdateColocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x04 \x01(\tH\x02R\aaddress\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_address\")\n" +
	"\x17DeleteColocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteColocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x15JoinColocationRequest\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\"(\n" +
	"\x16LeaveColocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x17LeaveColocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x11GetMembersRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\"G\n" +
	"\x12GetMembersResponse\x121\n" +
	"\amembers\x18\x01 \x03(\v2\x17.coloc.ColocationMemberR\amembers\"S\n" +
	"\x13RemoveMemberRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"~\n" +
	"\x17UpdateMemberRoleRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x04role\x18\x03 \x01(\x0e2\x11.coloc.MemberRoleR\x04role\"-\n" +
	"\x1bRegenerateInviteCodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x1cRegenerateInviteCodeResponse\x12\x1f\n" +
	"\vinvite_code\x18\x01 \x01(\tR\n" +
	"inviteCode\"R\n" +
	"\x15SendInvitationRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"=\n" +
	"\x16ListInvitationsRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\"N\n" +
	"\x17ListInvitationsResponse\x123\n" +
	"\vinvitations\x18\x01 \x03(\v2\x11.coloc.InvitationR\vinvitations\"c\n" +
	"\x17CancelInvitationRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12#\n" +
	"\rinvitation_id\x18\x02 \x01(\tR\finvitationId\"4\n" +
	"\x18CancelInvitationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf2\x02\n" +
	"\n" +
	"Colocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x04 \x01(\tH\x01R\aaddress\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x1f\n" +
	"\vinvite_code\x18\x06 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12=\n" +
	"\x11current_user_role\x18\t \x01(\x0e2\x11.coloc.MemberRoleR\x0fcurrentUserRole\x12!\n" +
	"\fmember_count\x18\n" +
	" \x01(\x05R\vmemberCountB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_address\"\x97\x02\n" +
	"\x10ColocationMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rcolocation_id\x18\x03 \x01(\tR\fcolocationId\x12%\n" +
	"\x04role\x18\x04 \x01(\x0e2\x11.coloc.MemberRoleR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\tR\bjoinedAt\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x10\n" +
	"\x03nom\x18\a \x01(\tR\x03nom\x12\x16\n" +
	"\x06prenom\x18\b \x01(\tR\x06prenom\x12\"\n" +
	"\n" +
	"avatar_url\x18\t \x01(\tH\x00R\tavatarUrl\x88\x01\x01B\r\n" +
	"\v_avatar_url\"\xf4\x01\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcolocation_id\x18\x02 \x01(\tR\fcolocationId\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x03 \x01(\tR\tinvitedBy\x12#\n" +
	"\rinvited_email\x18\x04 \x01(\tR\finvitedEmail\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.coloc.InvitationStatusR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt*X\n" +
	"\n" +
	"MemberRole\x12\x1b\n" +
	"\x17MEMBER_ROLE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MEMBER_ROLE_MEMBER\x10\x01\x12\x15\n" +
	"\x11MEMBER_ROLE_ADMIN\x10\x02*\xb3\x01\n" +
	"\x10InvitationStatus\x12!\n" +
	"\x1dINVITATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INVITATION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aINVITATION_STATUS_ACCEPTED\x10\x02\x12\x1e\n" +
	"\x1aINVITATION_STATUS_REJECTED\x10\x03\x12\x1d\n" +
	"\x19INVITATION_STATUS_EXPIRED\x10\x042\xc1\r\n" +
	"\x11ColocationService\x12b\n" +
	"\x10CreateColocation\x12\x1e.coloc.CreateColocationRequest\x1a\x11.coloc.Colocation\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/colocations\x12^\n" +
	"\rGetColocation\x12\x1b.coloc.GetColocationRequest\x1a\x11.coloc.Colocation\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/colocations/{id}\x12j\n" +
	"\x0fListColocations\x12\x1d.coloc.ListColocationsRequest\x1a\x1e.coloc.ListColocationsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/colocations\x12g\n" +
	"\x10UpdateColocation\x12\x1e.coloc.UpdateColocationRequest\x1a\x11.coloc.Colocation\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/colocations/{id}\x12r\n" +
	"\x10DeleteColocation\x12\x1e.coloc.DeleteColocationRequest\x1a\x1f.coloc.DeleteColocationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/colocations/{id}\x12c\n" +
	"\x0eJoinColocation\x12\x1c.coloc.JoinColocationRequest\x1a\x11.coloc.Colocation\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/colocations/join\x12x\n" +
	"\x0fLeaveColocation\x12\x1d.coloc.LeaveColocationRequest\x1a\x1e.coloc.LeaveColocationResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/colocations/{id}/leave\x12s\n" +
	"\n" +
	"GetMembers\x12\x18.coloc.GetMembersRequest\x1a\x19.coloc.GetMembersResponse\"0\x82\xd3\xe4\x93\x02*\x12(/api/colocations/{colocation_id}/members\x12\x83\x01\n" +
	"\fRemoveMember\x12\x1a.coloc.RemoveMemberRequest\x1a\x1b.coloc.RemoveMemberResponse\":\x82\xd3\xe4\x93\x024*2/api/colocations/{colocation_id}/members/{user_id}\x12\x8f\x01\n" +
	"\x10UpdateMemberRole\x12\x1e.coloc.UpdateMemberRoleRequest\x1a\x17.coloc.ColocationMember\"B\x82\xd3\xe4\x93\x02<:\x01*\x1a7/api/colocations/{colocation_id}/members/{user_id}/role\x12\x91\x01\n" +
	"\x14RegenerateInviteCode\x12\".coloc.RegenerateInviteCodeRequest\x1a#.coloc.RegenerateInviteCodeResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/colocations/{id}/regenerate-code\x12z\n" +
	"\x0eSendInvitation\x12\x1c.coloc.SendInvitationRequest\x1a\x11.coloc.Invitation\"7\x82\xd3\xe4\x93\x021:\x01*\",/api/colocations/{colocation_id}/invitations\x12\x86\x01\n" +
	"\x0fListInvitations\x12\x1d.coloc.ListInvitationsRequest\x1a\x1e.coloc.ListInvitationsResponse\"4\x82\xd3\xe4\x93\x02.\x12,/api/colocations/{colocation_id}/invitations\x12\x99\x01\n" +
	"\x10CancelInvitation\x12\x1e.coloc.CancelInvitationRequest\x1a\x1f.coloc.CancelInvitationResponse\"D\x82\xd3\xe4\x93\x02>*</api/colocations/{colocation_id}/invitations/{invitation_id}B,Z*github.com/vblanchet22/back_coloc/proto/pbb\x06proto3"

var (
	file_colocation_proto_rawDescOnce sync.Once
	file_colocation_proto_rawDescData []byte
)

func file_colocation_proto_rawDescGZIP() []byte {
	file_colocation_proto_rawDescOnce.Do(func() {
		file_colocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_colocation_proto_rawDesc), len(file_colocation_proto_rawDesc)))
	})
	return file_colocation_proto_rawDescData
}

var file_colocation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_colocation_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_colocation_proto_goTypes = []any{
	(MemberRole)(0),                      // 0: coloc.MemberRole
	(InvitationStatus)(0),                // 1: coloc.InvitationStatus
	(*CreateColocationRequest)(nil),      // 2: coloc.CreateColocationRequest
	(*GetColocationRequest)(nil),         // 3: coloc.GetColocationRequest
	(*ListColocationsRequest)(nil),       // 4: coloc.ListColocationsRequest
	(*ListColocationsResponse)(nil),      // 5: coloc.ListColocationsResponse
	(*UpdateColocationRequest)(nil),      // 6: coloc.UpdateColocationRequest
	(*DeleteColocationRequest)(nil),      // 7: coloc.DeleteColocationRequest
	(*DeleteColocationResponse)(nil),     // 8: coloc.DeleteColocationResponse
	(*JoinColocationRequest)(nil),        // 9: coloc.JoinColocationRequest
	(*LeaveColocationRequest)(nil),       // 10: coloc.LeaveColocationRequest
	(*LeaveColocationResponse)(nil),      // 11: coloc.LeaveColocationResponse
	(*GetMembersRequest)(nil),            // 12: coloc.GetMembersRequest
	(*GetMembersResponse)(nil),           // 13: coloc.GetMembersResponse
	(*RemoveMemberRequest)(nil),          // 14: coloc.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),         // 15: coloc.RemoveMemberResponse
	(*UpdateMemberRoleRequest)(nil),      // 16: coloc.UpdateMemberRoleRequest
	(*RegenerateInviteCodeRequest)(nil),  // 17: coloc.RegenerateInviteCodeRequest
	(*RegenerateInviteCodeResponse)(nil), // 18: coloc.RegenerateInviteCodeResponse
	(*SendInvitationRequest)(nil),        // 19: coloc.SendInvitationRequest
	(*ListInvitationsRequest)(nil),       // 20: coloc.ListInvitationsRequest
	(*ListInvitationsResponse)(nil),      // 21: coloc.ListInvitationsResponse
	(*CancelInvitationRequest)(nil),      // 22: coloc.CancelInvitationRequest
	(*CancelInvitationResponse)(nil),     // 23: coloc.CancelInvitationResponse
	(*Colocation)(nil),                   // 24: coloc.Colocation
	(*ColocationMember)(nil),             // 25: coloc.ColocationMember
	(*Invitation)(nil),                   // 26: coloc.Invitation
}
var file_colocation_proto_depIdxs = []int32{
	24, // 0: coloc.ListColocationsResponse.colocations:type_name -> coloc.Colocation
	25, // 1: coloc.GetMembersResponse.members:type_name -> coloc.ColocationMember
	0,  // 2: coloc.UpdateMemberRoleRequest.role:type_name -> coloc.MemberRole
	26, // 3: coloc.ListInvitationsResponse.invitations:type_name -> coloc.Invitation
	0,  // 4: coloc.Colocation.current_user_role:type_name -> coloc.MemberRole
	0,  // 5: coloc.ColocationMember.role:type_name -> coloc.MemberRole
	1,  // 6: coloc.Invitation.status:type_name -> coloc.InvitationStatus
	2,  // 7: coloc.ColocationService.CreateColocation:input_type -> coloc.CreateColocationRequest
	3,  // 8: coloc.ColocationService.GetColocation:input_type -> coloc.GetColocationRequest
	4,  // 9: coloc.ColocationService.ListColocations:input_type -> coloc.ListColocationsRequest
	6,  // 10: coloc.ColocationService.UpdateColocation:input_type -> coloc.UpdateColocationRequest
	7,  // 11: coloc.ColocationService.DeleteColocation:input_type -> coloc.DeleteColocationRequest
	9,  // 12: coloc.ColocationService.JoinColocation:input_type -> coloc.JoinColocationRequest
	10, // 13: coloc.ColocationService.LeaveColocation:input_type -> coloc.LeaveColocationRequest
	12, // 14: coloc.ColocationService.GetMembers:input_type -> coloc.GetMembersRequest
	14, // 15: coloc.ColocationService.RemoveMember:input_type -> coloc.RemoveMemberRequest
	16, // 16: coloc.ColocationService.UpdateMemberRole:input_type -> coloc.UpdateMemberRoleRequest
	17, // 17: coloc.ColocationService.RegenerateInviteCode:input_type -> coloc.RegenerateInviteCodeRequest
	19, // 18: coloc.ColocationService.SendInvitation:input_type -> coloc.SendInvitationRequest
	20, // 19: coloc.ColocationService.ListInvitations:input_type -> coloc.ListInvitationsRequest
	22, // 20: coloc.ColocationService.CancelInvitation:input_type -> coloc.CancelInvitationRequest
	24, // 21: coloc.ColocationService.CreateColocation:output_type -> coloc.Colocation
	24, // 22: coloc.ColocationService.GetColocation:output_type -> coloc.Colocation
	5,  // 23: coloc.ColocationService.ListColocations:output_type -> coloc.ListColocationsResponse
	24, // 24: coloc.ColocationService.UpdateColocation:output_type -> coloc.Colocation
	8,  // 25: coloc.ColocationService.DeleteColocation:output_type -> coloc.DeleteColocationResponse
	24, // 26: coloc.ColocationService.JoinColocation:output_type -> coloc.Colocation
	11, // 27: coloc.ColocationService.LeaveColocation:output_type -> coloc.LeaveColocationResponse
	13, // 28: coloc.ColocationService.GetMembers:output_type -> coloc.GetMembersResponse
	15, // 29: coloc.ColocationService.RemoveMember:output_type -> coloc.RemoveMemberResponse
	25, // 30: coloc.ColocationService.UpdateMemberRole:output_type -> coloc.ColocationMember
	18, // 31: coloc.ColocationService.RegenerateInviteCode:output_type -> coloc.RegenerateInviteCodeResponse
	26, // 32: coloc.ColocationService.SendInvitation:output_type -> coloc.Invitation
	21, // 33: coloc.ColocationService.ListInvitations:output_type -> coloc.ListInvitationsResponse
	23, // 34: coloc.ColocationService.CancelInvitation:output_type -> coloc.CancelInvitationResponse
	21, // [21:35] is the sub-list for method output_type
	7,  // [7:21] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_colocation_proto_init() }
func file_colocation_proto_init() {
	if File_colocation_proto != nil {
		return
	}
	file_colocation_proto_msgTypes[0].OneofWrappers = []any{}
	file_colocation_proto_msgTypes[4].OneofWrappers = []any{}
	file_colocation_proto_msgTypes[22].OneofWrappers = []any{}
	file_colocation_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_colocation_proto_rawDesc), len(file_colocation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_colocation_proto_goTypes,
		DependencyIndexes: file_colocation_proto_depIdxs,
		EnumInfos:         file_colocation_proto_enumTypes,
		MessageInfos:      file_colocation_proto_msgTypes,
	}.Build()
	File_colocation_proto = out.File
	file_colocation_proto_goTypes = nil
	file_colocation_proto_depIdxs = nil
}
