// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: decision.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionStatus int32

const (
	DecisionStatus_DECISION_STATUS_UNSPECIFIED DecisionStatus = 0
	DecisionStatus_DECISION_STATUS_OPEN        DecisionStatus = 1
	DecisionStatus_DECISION_STATUS_CLOSED      DecisionStatus = 2
)

// Enum value maps for DecisionStatus.
var (
	DecisionStatus_name = map[int32]string{
		0: "DECISION_STATUS_UNSPECIFIED",
		1: "DECISION_STATUS_OPEN",
		2: "DECISION_STATUS_CLOSED",
	}
	DecisionStatus_value = map[string]int32{
		"DECISION_STATUS_UNSPECIFIED": 0,
		"DECISION_STATUS_OPEN":        1,
		"DECISION_STATUS_CLOSED":      2,
	}
)

func (x DecisionStatus) Enum() *DecisionStatus {
	p := new(DecisionStatus)
	*p = x
	return p
}

func (x DecisionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_decision_proto_enumTypes[0].Descriptor()
}

func (DecisionStatus) Type() protoreflect.EnumType {
	return &file_decision_proto_enumTypes[0]
}

func (x DecisionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionStatus.Descriptor instead.
func (DecisionStatus) EnumDescriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{0}
}

type DecisionOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionOption) Reset() {
	*x = DecisionOption{}
	mi := &file_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionOption) ProtoMessage() {}

func (x *DecisionOption) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionOption.ProtoReflect.Descriptor instead.
func (*DecisionOption) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionOption) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DecisionOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`                                   // List of option texts
	Deadline      *string                `protobuf:"bytes,5,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`                           // Format: YYYY-MM-DD HH:MM
	AllowMultiple bool                   `protobuf:"varint,6,opt,name=allow_multiple,json=allowMultiple,proto3" json:"allow_multiple,omitempty"` // Allow multiple votes per user
	IsAnonymous   bool                   `protobuf:"varint,7,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`       // Hide who voted for what
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDecisionRequest) Reset() {
	*x = CreateDecisionRequest{}
	mi := &file_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDecisionRequest) ProtoMessage() {}

func (x *CreateDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDecisionRequest.ProtoReflect.Descriptor instead.
func (*CreateDecisionRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDecisionRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CreateDecisionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDecisionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateDecisionRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateDecisionRequest) GetDeadline() string {
	if x != nil && x.Deadline != nil {
		return *x.Deadline
	}
	return ""
}

func (x *CreateDecisionRequest) GetAllowMultiple() bool {
	if x != nil {
		return x.AllowMultiple
	}
	return false
}

func (x *CreateDecisionRequest) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

type GetDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDecisionRequest) Reset() {
	*x = GetDecisionRequest{}
	mi := &file_decision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecisionRequest) ProtoMessage() {}

func (x *GetDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecisionRequest.ProtoReflect.Descriptor instead.
func (*GetDecisionRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{2}
}

func (x *GetDecisionRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetDecisionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDecisionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Status        *DecisionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=coloc.DecisionStatus,oneof" json:"status,omitempty"`
	Page          *int32                 `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsRequest) Reset() {
	*x = ListDecisionsRequest{}
	mi := &file_decision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsRequest) ProtoMessage() {}

func (x *ListDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsRequest.ProtoReflect.Descriptor instead.
func (*ListDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{3}
}

func (x *ListDecisionsRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *ListDecisionsRequest) GetStatus() DecisionStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DecisionStatus_DECISION_STATUS_UNSPECIFIED
}

func (x *ListDecisionsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListDecisionsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListDecisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*Decision            `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsResponse) Reset() {
	*x = ListDecisionsResponse{}
	mi := &file_decision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsResponse) ProtoMessage() {}

func (x *ListDecisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsResponse.ProtoReflect.Descriptor instead.
func (*ListDecisionsResponse) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{4}
}

func (x *ListDecisionsResponse) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *ListDecisionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListDecisionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDecisionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"`
	Deadline      *string                `protobuf:"bytes,6,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	AllowMultiple *bool                  `protobuf:"varint,7,opt,name=allow_multiple,json=allowMultiple,proto3,oneof" json:"allow_multiple,omitempty"`
	IsAnonymous   *bool                  `protobuf:"varint,8,opt,name=is_anonymous,json=isAnonymous,proto3,oneof" json:"is_anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDecisionRequest) Reset() {
	*x = UpdateDecisionRequest{}
	mi := &file_decision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDecisionRequest) ProtoMessage() {}

func (x *UpdateDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDecisionRequest.ProtoReflect.Descriptor instead.
func (*UpdateDecisionRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDecisionRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *UpdateDecisionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDecisionRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateDecisionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateDecisionRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *UpdateDecisionRequest) GetDeadline() string {
	if x != nil && x.Deadline != nil {
		return *x.Deadline
	}
	return ""
}

func (x *UpdateDecisionRequest) GetAllowMultiple() bool {
	if x != nil && x.AllowMultiple != nil {
		return *x.AllowMultiple
	}
	return false
}

func (x *UpdateDecisionRequest) GetIsAnonymous() bool {
	if x != nil && x.IsAnonymous != nil {
		return *x.IsAnonymous
	}
	return false
}

type DeleteDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDecisionRequest) Reset() {
	*x = DeleteDecisionRequest{}
	mi := &file_decision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDecisionRequest) ProtoMessage() {}

func (x *DeleteDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDecisionRequest.ProtoReflect.Descriptor instead.
func (*DeleteDecisionRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteDecisionRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *DeleteDecisionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDecisionResponse) Reset() {
	*x = DeleteDecisionResponse{}
	mi := &file_decision_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDecisionResponse) ProtoMessage() {}

func (x *DeleteDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDecisionResponse.ProtoReflect.Descriptor instead.
func (*DeleteDecisionResponse) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDecisionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	DecisionId    string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	OptionIndices []int32                `protobuf:"varint,3,rep,packed,name=option_indices,json=optionIndices,proto3" json:"option_indices,omitempty"` // Can vote for multiple if allow_multiple
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_decision_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{8}
}

func (x *VoteRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *VoteRequest) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *VoteRequest) GetOptionIndices() []int32 {
	if x != nil {
		return x.OptionIndices
	}
	return nil
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_decision_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{9}
}

func (x *VoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CloseDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseDecisionRequest) Reset() {
	*x = CloseDecisionRequest{}
	mi := &file_decision_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDecisionRequest) ProtoMessage() {}

func (x *CloseDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDecisionRequest.ProtoReflect.Descriptor instead.
func (*CloseDecisionRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{10}
}

func (x *CloseDecisionRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CloseDecisionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultsRequest) Reset() {
	*x = GetResultsRequest{}
	mi := &file_decision_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsRequest) ProtoMessage() {}

func (x *GetResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsRequest.ProtoReflect.Descriptor instead.
func (*GetResultsRequest) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{11}
}

func (x *GetResultsRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetResultsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResultsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DecisionId         string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Status             DecisionStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=coloc.DecisionStatus" json:"status,omitempty"`
	Results            []*OptionResult        `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	TotalVotes         int32                  `protobuf:"varint,4,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	TotalVoters        int32                  `protobuf:"varint,5,opt,name=total_voters,json=totalVoters,proto3" json:"total_voters,omitempty"`
	WinningOptionIndex *int32                 `protobuf:"varint,6,opt,name=winning_option_index,json=winningOptionIndex,proto3,oneof" json:"winning_option_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetResultsResponse) Reset() {
	*x = GetResultsResponse{}
	mi := &file_decision_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsResponse) ProtoMessage() {}

func (x *GetResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsResponse.ProtoReflect.Descriptor instead.
func (*GetResultsResponse) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{12}
}

func (x *GetResultsResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *GetResultsResponse) GetStatus() DecisionStatus {
	if x != nil {
		return x.Status
	}
	return DecisionStatus_DECISION_STATUS_UNSPECIFIED
}

func (x *GetResultsResponse) GetResults() []*OptionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetResultsResponse) GetTotalVotes() int32 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

func (x *GetResultsResponse) GetTotalVoters() int32 {
	if x != nil {
		return x.TotalVoters
	}
	return 0
}

func (x *GetResultsResponse) GetWinningOptionIndex() int32 {
	if x != nil && x.WinningOptionIndex != nil {
		return *x.WinningOptionIndex
	}
	return 0
}

type OptionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionIndex   int32                  `protobuf:"varint,1,opt,name=option_index,json=optionIndex,proto3" json:"option_index,omitempty"`
	OptionText    string                 `protobuf:"bytes,2,opt,name=option_text,json=optionText,proto3" json:"option_text,omitempty"`
	VoteCount     int32                  `protobuf:"varint,3,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Voters        []*Voter               `protobuf:"bytes,5,rep,name=voters,proto3" json:"voters,omitempty"` // Empty if is_anonymous
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionResult) Reset() {
	*x = OptionResult{}
	mi := &file_decision_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionResult) ProtoMessage() {}

func (x *OptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionResult.ProtoReflect.Descriptor instead.
func (*OptionResult) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{13}
}

func (x *OptionResult) GetOptionIndex() int32 {
	if x != nil {
		return x.OptionIndex
	}
	return 0
}

func (x *OptionResult) GetOptionText() string {
	if x != nil {
		return x.OptionText
	}
	return ""
}

func (x *OptionResult) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *OptionResult) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *OptionResult) GetVoters() []*Voter {
	if x != nil {
		return x.Voters
	}
	return nil
}

type Voter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNom       string                 `protobuf:"bytes,2,opt,name=user_nom,json=userNom,proto3" json:"user_nom,omitempty"`
	UserPrenom    string                 `protobuf:"bytes,3,opt,name=user_prenom,json=userPrenom,proto3" json:"user_prenom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Voter) Reset() {
	*x = Voter{}
	mi := &file_decision_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Voter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voter) ProtoMessage() {}

func (x *Voter) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voter.ProtoReflect.Descriptor instead.
func (*Voter) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{14}
}

func (x *Voter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Voter) GetUserNom() string {
	if x != nil {
		return x.UserNom
	}
	return ""
}

func (x *Voter) GetUserPrenom() string {
	if x != nil {
		return x.UserPrenom
	}
	return ""
}

type Decision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ColocationId    string                 `protobuf:"bytes,2,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedByNom    string                 `protobuf:"bytes,4,opt,name=created_by_nom,json=createdByNom,proto3" json:"created_by_nom,omitempty"`
	CreatedByPrenom string                 `protobuf:"bytes,5,opt,name=created_by_prenom,json=createdByPrenom,proto3" json:"created_by_prenom,omitempty"`
	Title           string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description     *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Options         []*DecisionOption      `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty"`
	Status          DecisionStatus         `protobuf:"varint,9,opt,name=status,proto3,enum=coloc.DecisionStatus" json:"status,omitempty"`
	Deadline        *string                `protobuf:"bytes,10,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	AllowMultiple   bool                   `protobuf:"varint,11,opt,name=allow_multiple,json=allowMultiple,proto3" json:"allow_multiple,omitempty"`
	IsAnonymous     bool                   `protobuf:"varint,12,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	VoteCount       int32                  `protobuf:"varint,13,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	HasVoted        bool                   `protobuf:"varint,14,opt,name=has_voted,json=hasVoted,proto3" json:"has_voted,omitempty"`           // Whether current user has voted
	UserVotes       []int32                `protobuf:"varint,15,rep,packed,name=user_votes,json=userVotes,proto3" json:"user_votes,omitempty"` // Current user's votes (option indices)
	CreatedAt       string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_decision_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_decision_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_decision_proto_rawDescGZIP(), []int{15}
}

func (x *Decision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Decision) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *Decision) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Decision) GetCreatedByNom() string {
	if x != nil {
		return x.CreatedByNom
	}
	return ""
}

func (x *Decision) GetCreatedByPrenom() string {
	if x != nil {
		return x.CreatedByPrenom
	}
	return ""
}

func (x *Decision) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Decision) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Decision) GetOptions() []*DecisionOption {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Decision) GetStatus() DecisionStatus {
	if x != nil {
		return x.Status
	}
	return DecisionStatus_DECISION_STATUS_UNSPECIFIED
}

func (x *Decision) GetDeadline() string {
	if x != nil && x.Deadline != nil {
		return *x.Deadline
	}
	return ""
}

func (x *Decision) GetAllowMultiple() bool {
	if x != nil {
		return x.AllowMultiple
	}
	return false
}

func (x *Decision) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *Decision) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *Decision) GetHasVoted() bool {
	if x != nil {
		return x.HasVoted
	}
	return false
}

func (x *Decision) GetUserVotes() []int32 {
	if x != nil {
		return x.UserVotes
	}
	return nil
}

func (x *Decision) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_decision_proto protoreflect.FileDescriptor

const file_decision_proto_rawDesc = "" +
	"\n" +
	"\x0edecision.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\":\n" +
	"\x0eDecisionOption\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x9b\x02\n" +
	"\x15CreateDecisionRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\x12\x1f\n" +
	"\bdeadline\x18\x05 \x01(\tH\x01R\bdeadline\x88\x01\x01\x12%\n" +
	"\x0eallow_multiple\x18\x06 \x01(\bR\rallowMultiple\x12!\n" +
	"\fis_anonymous\x18\a \x01(\bR\visAnonymousB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_deadline\"I\n" +
	"\x12GetDecisionRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xcc\x01\n" +
	"\x14ListDecisionsRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.coloc.DecisionStatusH\x00R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x03 \x01(\x05H\x01R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05H\x02R\bpageSize\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\x98\x01\n" +
	"\x15ListDecisionsResponse\x12-\n" +
	"\tdecisions\x18\x01 \x03(\v2\x0f.coloc.DecisionR\tdecisions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xe8\x02\n" +
	"\x15UpdateDecisionRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\x12\x1f\n" +
	"\bdeadline\x18\x06 \x01(\tH\x02R\bdeadline\x88\x01\x01\x12*\n" +
	"\x0eallow_multiple\x18\a \x01(\bH\x03R\rallowMultiple\x88\x01\x01\x12&\n" +
	"\fis_anonymous\x18\b \x01(\bH\x04R\visAnonymous\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_deadlineB\x11\n" +
	"\x0f_allow_multipleB\x0f\n" +
	"\r_is_anonymous\"L\n" +
	"\x15DeleteDecisionRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"2\n" +
	"\x16DeleteDecisionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"z\n" +
	"\vVoteRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12%\n" +
	"\x0eoption_indices\x18\x03 \x03(\x05R\roptionIndices\"(\n" +
	"\fVoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x14CloseDecisionRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"H\n" +
	"\x11GetResultsRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xa7\x02\n" +
	"\x12GetResultsResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.coloc.DecisionStatusR\x06status\x12-\n" +
	"\aresults\x18\x03 \x03(\v2\x13.coloc.OptionResultR\aresults\x12\x1f\n" +
	"\vtotal_votes\x18\x04 \x01(\x05R\n" +
	"totalVotes\x12!\n" +
	"\ftotal_voters\x18\x05 \x01(\x05R\vtotalVoters\x125\n" +
	"\x14winning_option_index\x18\x06 \x01(\x05H\x00R\x12winningOptionIndex\x88\x01\x01B\x17\n" +
	"\x15_winning_option_index\"\xb7\x01\n" +
	"\fOptionResult\x12!\n" +
	"\foption_index\x18\x01 \x01(\x05R\voptionIndex\x12\x1f\n" +
	"\voption_text\x18\x02 \x01(\tR\n" +
	"optionText\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x03 \x01(\x05R\tvoteCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\x12$\n" +
	"\x06voters\x18\x05 \x03(\v2\f.coloc.VoterR\x06voters\"\\\n" +
	"\x05Voter\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_nom\x18\x02 \x01(\tR\auserNom\x12\x1f\n" +
	"\vuser_prenom\x18\x03 \x01(\tR\n" +
	"userPrenom\"\xcf\x04\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcolocation_id\x18\x02 \x01(\tR\fcolocationId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\tR\tcreatedBy\x12$\n" +
	"\x0ecreated_by_nom\x18\x04 \x01(\tR\fcreatedByNom\x12*\n" +
	"\x11created_by_prenom\x18\x05 \x01(\tR\x0fcreatedByPrenom\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x00R\vdescription\x88\x01\x01\x12/\n" +
	"\aoptions\x18\b \x03(\v2\x15.coloc.DecisionOptionR\aoptions\x12-\n" +
	"\x06status\x18\t \x01(\x0e2\x15.coloc.DecisionStatusR\x06status\x12\x1f\n" +
	"\bdeadline\x18\n" +
	" \x01(\tH\x01R\bdeadline\x88\x01\x01\x12%\n" +
	"\x0eallow_multiple\x18\v \x01(\bR\rallowMultiple\x12!\n" +
	"\fis_anonymous\x18\f \x01(\bR\visAnonymous\x12\x1d\n" +
	"\n" +
	"vote_count\x18\r \x01(\x05R\tvoteCount\x12\x1b\n" +
	"\thas_voted\x18\x0e \x01(\bR\bhasVoted\x12\x1d\n" +
	"\n" +
	"user_votes\x18\x0f \x03(\x05R\tuserVotes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAtB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_deadline*g\n" +
	"\x0eDecisionStatus\x12\x1f\n" +
	"\x1bDECISION_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DECISION_STATUS_OPEN\x10\x01\x12\x1a\n" +
	"\x16DECISION_STATUS_CLOSED\x10\x022\x84\b\n" +
	"\x0fDecisionService\x12v\n" +
	"\x0eCreateDecision\x12\x1c.coloc.CreateDecisionRequest\x1a\x0f.coloc.Decision\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/colocations/{colocation_id}/decisions\x12r\n" +
	"\vGetDecision\x12\x19.coloc.GetDecisionRequest\x1a\x0f.coloc.Decision\"7\x82\xd3\xe4\x93\x021\x12//api/colocations/{colocation_id}/decisions/{id}\x12~\n" +
	"\rListDecisions\x12\x1b.coloc.ListDecisionsRequest\x1a\x1c.coloc.ListDecisionsResponse\"2\x82\xd3\xe4\x93\x02,\x12*/api/colocations/{colocation_id}/decisions\x12{\n" +
	"\x0eUpdateDecision\x12\x1c.coloc.UpdateDecisionRequest\x1a\x0f.coloc.Decision\":\x82\xd3\xe4\x93\x024:\x01*\x1a//api/colocations/{colocation_id}/decisions/{id}\x12\x86\x01\n" +
	"\x0eDeleteDecision\x12\x1c.coloc.DeleteDecisionRequest\x1a\x1d.coloc.DeleteDecisionResponse\"7\x82\xd3\xe4\x93\x021*//api/colocations/{colocation_id}/decisions/{id}\x12y\n" +
	"\x04Vote\x12\x12.coloc.VoteRequest\x1a\x13.coloc.VoteResponse\"H\x82\xd3\xe4\x93\x02B:\x01*\"=/api/colocations/{colocation_id}/decisions/{decision_id}/vote\x12\x7f\n" +
	"\rCloseDecision\x12\x1b.coloc.CloseDecisionRequest\x1a\x0f.coloc.Decision\"@\x82\xd3\xe4\x93\x02::\x01*\"5/api/colocations/{colocation_id}/decisions/{id}/close\x12\x82\x01\n" +
	"\n" +
	"GetResults\x12\x18.coloc.GetResultsRequest\x1a\x19.coloc.GetResultsResponse\"?\x82\xd3\xe4\x93\x029\x127/api/colocations/{colocation_id}/decisions/{id}/resultsB,Z*github.com/vblanchet22/back_coloc/proto/pbb\x06proto3"

var (
	file_decision_proto_rawDescOnce sync.Once
	file_decision_proto_rawDescData []byte
)

func file_decision_proto_rawDescGZIP() []byte {
	file_decision_proto_rawDescOnce.Do(func() {
		file_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_decision_proto_rawDesc), len(file_decision_proto_rawDesc)))
	})
	return file_decision_proto_rawDescData
}

var file_decision_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_decision_proto_goTypes = []any{
	(DecisionStatus)(0),            // 0: coloc.DecisionStatus
	(*DecisionOption)(nil),         // 1: coloc.DecisionOption
	(*CreateDecisionRequest)(nil),  // 2: coloc.CreateDecisionRequest
	(*GetDecisionRequest)(nil),     // 3: coloc.GetDecisionRequest
	(*ListDecisionsRequest)(nil),   // 4: coloc.ListDecisionsRequest
	(*ListDecisionsResponse)(nil),  // 5: coloc.ListDecisionsResponse
	(*UpdateDecisionRequest)(nil),  // 6: coloc.UpdateDecisionRequest
	(*DeleteDecisionRequest)(nil),  // 7: coloc.DeleteDecisionRequest
	(*DeleteDecisionResponse)(nil), // 8: coloc.DeleteDecisionResponse
	(*VoteRequest)(nil),            // 9: coloc.VoteRequest
	(*VoteResponse)(nil),           // 10: coloc.VoteResponse
	(*CloseDecisionRequest)(nil),   // 11: coloc.CloseDecisionRequest
	(*GetResultsRequest)(nil),      // 12: coloc.GetResultsRequest
	(*GetResultsResponse)(nil),     // 13: coloc.GetResultsResponse
	(*OptionResult)(nil),           // 14: coloc.OptionResult
	(*Voter)(nil),                  // 15: coloc.Voter
	(*Decision)(nil),               // 16: coloc.Decision
}
var file_decision_proto_depIdxs = []int32{
	0,  // 0: coloc.ListDecisionsRequest.status:type_name -> coloc.DecisionStatus
	16, // 1: coloc.ListDecisionsResponse.decisions:type_name -> coloc.Decision
	0,  // 2: coloc.GetResultsResponse.status:type_name -> coloc.DecisionStatus
	14, // 3: coloc.GetResultsResponse.results:type_name -> coloc.OptionResult
	15, // 4: coloc.OptionResult.voters:type_name -> coloc.Voter
	1,  // 5: coloc.Decision.options:type_name -> coloc.DecisionOption
	0,  // 6: coloc.Decision.status:type_name -> coloc.DecisionStatus
	2,  // 7: coloc.DecisionService.CreateDecision:input_type -> coloc.CreateDecisionRequest
	3,  // 8: coloc.DecisionService.GetDecision:input_type -> coloc.GetDecisionRequest
	4,  // 9: coloc.DecisionService.ListDecisions:input_type -> coloc.ListDecisionsRequest
	6,  // 10: coloc.DecisionService.UpdateDecision:input_type -> coloc.UpdateDecisionRequest
	7,  // 11: coloc.DecisionService.DeleteDecision:input_type -> coloc.DeleteDecisionRequest
	9,  // 12: coloc.DecisionService.Vote:input_type -> coloc.VoteRequest
	11, // 13: coloc.DecisionService.CloseDecision:input_type -> coloc.CloseDecisionRequest
	12, // 14: coloc.DecisionService.GetResults:input_type -> coloc.GetResultsRequest
	16, // 15: coloc.DecisionService.CreateDecision:output_type -> coloc.Decision
	16, // 16: coloc.DecisionService.GetDecision:output_type -> coloc.Decision
	5,  // 17: coloc.DecisionService.ListDecisions:output_type -> coloc.ListDecisionsResponse
	16, // 18: coloc.DecisionService.UpdateDecision:output_type -> coloc.Decision
	8,  // 19: coloc.DecisionService.DeleteDecision:output_type -> coloc.DeleteDecisionResponse
	10, // 20: coloc.DecisionService.Vote:output_type -> coloc.VoteResponse
	16, // 21: coloc.DecisionService.CloseDecision:output_type -> coloc.Decision
	13, // 22: coloc.DecisionService.GetResults:output_type -> coloc.GetResultsResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_decision_proto_init() }
func file_decision_proto_init() {
	if File_decision_proto != nil {
		return
	}
	file_decision_proto_msgTypes[1].OneofWrappers = []any{}
	file_decision_proto_msgTypes[3].OneofWrappers = []any{}
	file_decision_proto_msgTypes[5].OneofWrappers = []any{}
	file_decision_proto_msgTypes[12].OneofWrappers = []any{}
	file_decision_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decision_proto_rawDesc), len(file_decision_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decision_proto_goTypes,
		DependencyIndexes: file_decision_proto_depIdxs,
		EnumInfos:         file_decision_proto_enumTypes,
		MessageInfos:      file_decision_proto_msgTypes,
	}.Build()
	File_decision_proto = out.File
	file_decision_proto_goTypes = nil
	file_decision_proto_depIdxs = nil
}
