// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: expense.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SplitType int32

const (
	SplitType_SPLIT_TYPE_UNSPECIFIED SplitType = 0
	SplitType_SPLIT_TYPE_EQUAL       SplitType = 1 // Equal split among all members
	SplitType_SPLIT_TYPE_PERCENTAGE  SplitType = 2 // Custom percentage per member
	SplitType_SPLIT_TYPE_CUSTOM      SplitType = 3 // Fixed amount per member
)

// Enum value maps for SplitType.
var (
	SplitType_name = map[int32]string{
		0: "SPLIT_TYPE_UNSPECIFIED",
		1: "SPLIT_TYPE_EQUAL",
		2: "SPLIT_TYPE_PERCENTAGE",
		3: "SPLIT_TYPE_CUSTOM",
	}
	SplitType_value = map[string]int32{
		"SPLIT_TYPE_UNSPECIFIED": 0,
		"SPLIT_TYPE_EQUAL":       1,
		"SPLIT_TYPE_PERCENTAGE":  2,
		"SPLIT_TYPE_CUSTOM":      3,
	}
)

func (x SplitType) Enum() *SplitType {
	p := new(SplitType)
	*p = x
	return p
}

func (x SplitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitType) Descriptor() protoreflect.EnumDescriptor {
	return file_expense_proto_enumTypes[0].Descriptor()
}

func (SplitType) Type() protoreflect.EnumType {
	return &file_expense_proto_enumTypes[0]
}

func (x SplitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SplitType.Descriptor instead.
func (SplitType) EnumDescriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{0}
}

type Recurrence int32

const (
	Recurrence_RECURRENCE_UNSPECIFIED Recurrence = 0
	Recurrence_RECURRENCE_DAILY       Recurrence = 1
	Recurrence_RECURRENCE_WEEKLY      Recurrence = 2
	Recurrence_RECURRENCE_MONTHLY     Recurrence = 3
	Recurrence_RECURRENCE_YEARLY      Recurrence = 4
)

// Enum value maps for Recurrence.
var (
	Recurrence_name = map[int32]string{
		0: "RECURRENCE_UNSPECIFIED",
		1: "RECURRENCE_DAILY",
		2: "RECURRENCE_WEEKLY",
		3: "RECURRENCE_MONTHLY",
		4: "RECURRENCE_YEARLY",
	}
	Recurrence_value = map[string]int32{
		"RECURRENCE_UNSPECIFIED": 0,
		"RECURRENCE_DAILY":       1,
		"RECURRENCE_WEEKLY":      2,
		"RECURRENCE_MONTHLY":     3,
		"RECURRENCE_YEARLY":      4,
	}
)

func (x Recurrence) Enum() *Recurrence {
	p := new(Recurrence)
	*p = x
	return p
}

func (x Recurrence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Recurrence) Descriptor() protoreflect.EnumDescriptor {
	return file_expense_proto_enumTypes[1].Descriptor()
}

func (Recurrence) Type() protoreflect.EnumType {
	return &file_expense_proto_enumTypes[1]
}

func (x Recurrence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Recurrence.Descriptor instead.
func (Recurrence) EnumDescriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{1}
}

type ExpenseSplit struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UserId     string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount     float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`                       // Amount owed by this user
	Percentage float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`               // Percentage (for SPLIT_TYPE_PERCENTAGE)
	IsSettled  bool                   `protobuf:"varint,4,opt,name=is_settled,json=isSettled,proto3" json:"is_settled,omitempty"` // Whether this split has been settled
	// User details
	UserNom       string `protobuf:"bytes,5,opt,name=user_nom,json=userNom,proto3" json:"user_nom,omitempty"`
	UserPrenom    string `protobuf:"bytes,6,opt,name=user_prenom,json=userPrenom,proto3" json:"user_prenom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseSplit) Reset() {
	*x = ExpenseSplit{}
	mi := &file_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseSplit) ProtoMessage() {}

func (x *ExpenseSplit) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseSplit.ProtoReflect.Descriptor instead.
func (*ExpenseSplit) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseSplit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExpenseSplit) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExpenseSplit) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ExpenseSplit) GetIsSettled() bool {
	if x != nil {
		return x.IsSettled
	}
	return false
}

func (x *ExpenseSplit) GetUserNom() string {
	if x != nil {
		return x.UserNom
	}
	return ""
}

func (x *ExpenseSplit) GetUserPrenom() string {
	if x != nil {
		return x.UserPrenom
	}
	return ""
}

type CreateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SplitType     SplitType              `protobuf:"varint,6,opt,name=split_type,json=splitType,proto3,enum=coloc.SplitType" json:"split_type,omitempty"`
	Splits        []*ExpenseSplitInput   `protobuf:"bytes,7,rep,name=splits,proto3" json:"splits,omitempty"`                              // Required for percentage/custom
	ExpenseDate   string                 `protobuf:"bytes,8,opt,name=expense_date,json=expenseDate,proto3" json:"expense_date,omitempty"` // Format: YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseRequest) Reset() {
	*x = CreateExpenseRequest{}
	mi := &file_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseRequest) ProtoMessage() {}

func (x *CreateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExpenseRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CreateExpenseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateExpenseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateExpenseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateExpenseRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateExpenseRequest) GetSplitType() SplitType {
	if x != nil {
		return x.SplitType
	}
	return SplitType_SPLIT_TYPE_UNSPECIFIED
}

func (x *CreateExpenseRequest) GetSplits() []*ExpenseSplitInput {
	if x != nil {
		return x.Splits
	}
	return nil
}

func (x *CreateExpenseRequest) GetExpenseDate() string {
	if x != nil {
		return x.ExpenseDate
	}
	return ""
}

type ExpenseSplitInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`         // For SPLIT_TYPE_CUSTOM
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"` // For SPLIT_TYPE_PERCENTAGE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseSplitInput) Reset() {
	*x = ExpenseSplitInput{}
	mi := &file_expense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseSplitInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseSplitInput) ProtoMessage() {}

func (x *ExpenseSplitInput) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseSplitInput.ProtoReflect.Descriptor instead.
func (*ExpenseSplitInput) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{2}
}

func (x *ExpenseSplitInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExpenseSplitInput) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExpenseSplitInput) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type GetExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpenseRequest) Reset() {
	*x = GetExpenseRequest{}
	mi := &file_expense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseRequest) ProtoMessage() {}

func (x *GetExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpenseRequest.ProtoReflect.Descriptor instead.
func (*GetExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{3}
}

func (x *GetExpenseRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListExpensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	CategoryId    *string                `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	PaidBy        *string                `protobuf:"bytes,3,opt,name=paid_by,json=paidBy,proto3,oneof" json:"paid_by,omitempty"`
	StartDate     *string                `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate       *string                `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	Page          *int32                 `protobuf:"varint,6,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpensesRequest) Reset() {
	*x = ListExpensesRequest{}
	mi := &file_expense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpensesRequest) ProtoMessage() {}

func (x *ListExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpensesRequest.ProtoReflect.Descriptor instead.
func (*ListExpensesRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{4}
}

func (x *ListExpensesRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *ListExpensesRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *ListExpensesRequest) GetPaidBy() string {
	if x != nil && x.PaidBy != nil {
		return *x.PaidBy
	}
	return ""
}

func (x *ListExpensesRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *ListExpensesRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *ListExpensesRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListExpensesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListExpensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expenses      []*Expense             `protobuf:"bytes,1,rep,name=expenses,proto3" json:"expenses,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExpensesResponse) Reset() {
	*x = ListExpensesResponse{}
	mi := &file_expense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExpensesResponse) ProtoMessage() {}

func (x *ListExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExpensesResponse.ProtoReflect.Descriptor instead.
func (*ListExpensesResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{5}
}

func (x *ListExpensesResponse) GetExpenses() []*Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

func (x *ListExpensesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListExpensesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListExpensesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Amount        *float64               `protobuf:"fixed64,5,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	CategoryId    *string                `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	SplitType     *SplitType             `protobuf:"varint,7,opt,name=split_type,json=splitType,proto3,enum=coloc.SplitType,oneof" json:"split_type,omitempty"`
	Splits        []*ExpenseSplitInput   `protobuf:"bytes,8,rep,name=splits,proto3" json:"splits,omitempty"`
	ExpenseDate   *string                `protobuf:"bytes,9,opt,name=expense_date,json=expenseDate,proto3,oneof" json:"expense_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpenseRequest) Reset() {
	*x = UpdateExpenseRequest{}
	mi := &file_expense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseRequest) ProtoMessage() {}

func (x *UpdateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateExpenseRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *UpdateExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExpenseRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateExpenseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateExpenseRequest) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *UpdateExpenseRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *UpdateExpenseRequest) GetSplitType() SplitType {
	if x != nil && x.SplitType != nil {
		return *x.SplitType
	}
	return SplitType_SPLIT_TYPE_UNSPECIFIED
}

func (x *UpdateExpenseRequest) GetSplits() []*ExpenseSplitInput {
	if x != nil {
		return x.Splits
	}
	return nil
}

func (x *UpdateExpenseRequest) GetExpenseDate() string {
	if x != nil && x.ExpenseDate != nil {
		return *x.ExpenseDate
	}
	return ""
}

type DeleteExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseRequest) Reset() {
	*x = DeleteExpenseRequest{}
	mi := &file_expense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseRequest) ProtoMessage() {}

func (x *DeleteExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteExpenseRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *DeleteExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseResponse) Reset() {
	*x = DeleteExpenseResponse{}
	mi := &file_expense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseResponse) ProtoMessage() {}

func (x *DeleteExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteExpenseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Expense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ColocationId  string                 `protobuf:"bytes,2,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	PaidBy        string                 `protobuf:"bytes,3,opt,name=paid_by,json=paidBy,proto3" json:"paid_by,omitempty"`
	PaidByNom     string                 `protobuf:"bytes,4,opt,name=paid_by_nom,json=paidByNom,proto3" json:"paid_by_nom,omitempty"`
	PaidByPrenom  string                 `protobuf:"bytes,5,opt,name=paid_by_prenom,json=paidByPrenom,proto3" json:"paid_by_prenom,omitempty"`
	CategoryId    string                 `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,7,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,10,opt,name=amount,proto3" json:"amount,omitempty"`
	SplitType     SplitType              `protobuf:"varint,11,opt,name=split_type,json=splitType,proto3,enum=coloc.SplitType" json:"split_type,omitempty"`
	ExpenseDate   string                 `protobuf:"bytes,12,opt,name=expense_date,json=expenseDate,proto3" json:"expense_date,omitempty"`
	RecurringId   *string                `protobuf:"bytes,13,opt,name=recurring_id,json=recurringId,proto3,oneof" json:"recurring_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Splits        []*ExpenseSplit        `protobuf:"bytes,15,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_expense_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expense.ProtoReflect.Descriptor instead.
func (*Expense) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{9}
}

func (x *Expense) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expense) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *Expense) GetPaidBy() string {
	if x != nil {
		return x.PaidBy
	}
	return ""
}

func (x *Expense) GetPaidByNom() string {
	if x != nil {
		return x.PaidByNom
	}
	return ""
}

func (x *Expense) GetPaidByPrenom() string {
	if x != nil {
		return x.PaidByPrenom
	}
	return ""
}

func (x *Expense) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Expense) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Expense) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Expense) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Expense) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Expense) GetSplitType() SplitType {
	if x != nil {
		return x.SplitType
	}
	return SplitType_SPLIT_TYPE_UNSPECIFIED
}

func (x *Expense) GetExpenseDate() string {
	if x != nil {
		return x.ExpenseDate
	}
	return ""
}

func (x *Expense) GetRecurringId() string {
	if x != nil && x.RecurringId != nil {
		return *x.RecurringId
	}
	return ""
}

func (x *Expense) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Expense) GetSplits() []*ExpenseSplit {
	if x != nil {
		return x.Splits
	}
	return nil
}

type CreateRecurringExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SplitType     SplitType              `protobuf:"varint,6,opt,name=split_type,json=splitType,proto3,enum=coloc.SplitType" json:"split_type,omitempty"`
	Splits        []*ExpenseSplitInput   `protobuf:"bytes,7,rep,name=splits,proto3" json:"splits,omitempty"`
	Recurrence    Recurrence             `protobuf:"varint,8,opt,name=recurrence,proto3,enum=coloc.Recurrence" json:"recurrence,omitempty"`
	StartDate     string                 `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *string                `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecurringExpenseRequest) Reset() {
	*x = CreateRecurringExpenseRequest{}
	mi := &file_expense_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecurringExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecurringExpenseRequest) ProtoMessage() {}

func (x *CreateRecurringExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecurringExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateRecurringExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRecurringExpenseRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CreateRecurringExpenseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRecurringExpenseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRecurringExpenseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateRecurringExpenseRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateRecurringExpenseRequest) GetSplitType() SplitType {
	if x != nil {
		return x.SplitType
	}
	return SplitType_SPLIT_TYPE_UNSPECIFIED
}

func (x *CreateRecurringExpenseRequest) GetSplits() []*ExpenseSplitInput {
	if x != nil {
		return x.Splits
	}
	return nil
}

func (x *CreateRecurringExpenseRequest) GetRecurrence() Recurrence {
	if x != nil {
		return x.Recurrence
	}
	return Recurrence_RECURRENCE_UNSPECIFIED
}

func (x *CreateRecurringExpenseRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateRecurringExpenseRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

type ListRecurringExpensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecurringExpensesRequest) Reset() {
	*x = ListRecurringExpensesRequest{}
	mi := &file_expense_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecurringExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecurringExpensesRequest) ProtoMessage() {}

func (x *ListRecurringExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecurringExpensesRequest.ProtoReflect.Descriptor instead.
func (*ListRecurringExpensesRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{11}
}

func (x *ListRecurringExpensesRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

type ListRecurringExpensesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RecurringExpenses []*RecurringExpense    `protobuf:"bytes,1,rep,name=recurring_expenses,json=recurringExpenses,proto3" json:"recurring_expenses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRecurringExpensesResponse) Reset() {
	*x = ListRecurringExpensesResponse{}
	mi := &file_expense_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecurringExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecurringExpensesResponse) ProtoMessage() {}

func (x *ListRecurringExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecurringExpensesResponse.ProtoReflect.Descriptor instead.
func (*ListRecurringExpensesResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{12}
}

func (x *ListRecurringExpensesResponse) GetRecurringExpenses() []*RecurringExpense {
	if x != nil {
		return x.RecurringExpenses
	}
	return nil
}

type UpdateRecurringExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Amount        *float64               `protobuf:"fixed64,5,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	CategoryId    *string                `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	SplitType     *SplitType             `protobuf:"varint,7,opt,name=split_type,json=splitType,proto3,enum=coloc.SplitType,oneof" json:"split_type,omitempty"`
	Splits        []*ExpenseSplitInput   `protobuf:"bytes,8,rep,name=splits,proto3" json:"splits,omitempty"`
	Recurrence    *Recurrence            `protobuf:"varint,9,opt,name=recurrence,proto3,enum=coloc.Recurrence,oneof" json:"recurrence,omitempty"`
	EndDate       *string                `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	IsActive      *bool                  `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecurringExpenseRequest) Reset() {
	*x = UpdateRecurringExpenseRequest{}
	mi := &file_expense_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecurringExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecurringExpenseRequest) ProtoMessage() {}

func (x *UpdateRecurringExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecurringExpenseRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecurringExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRecurringExpenseRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *UpdateRecurringExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRecurringExpenseRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateRecurringExpenseRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRecurringExpenseRequest) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *UpdateRecurringExpenseRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *UpdateRecurringExpenseRequest) GetSplitType() SplitType {
	if x != nil && x.SplitType != nil {
		return *x.SplitType
	}
	return SplitType_SPLIT_TYPE_UNSPECIFIED
}

func (x *UpdateRecurringExpenseRequest) GetSplits() []*ExpenseSplitInput {
	if x != nil {
		return x.Splits
	}
	return nil
}

func (x *UpdateRecurringExpenseRequest) GetRecurrence() Recurrence {
	if x != nil && x.Recurrence != nil {
		return *x.Recurrence
	}
	return Recurrence_RECURRENCE_UNSPECIFIED
}

func (x *UpdateRecurringExpenseRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *UpdateRecurringExpenseRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

type DeleteRecurringExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecurringExpenseRequest) Reset() {
	*x = DeleteRecurringExpenseRequest{}
	mi := &file_expense_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecurringExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecurringExpenseRequest) ProtoMessage() {}

func (x *DeleteRecurringExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecurringExpenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecurringExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRecurringExpenseRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *DeleteRecurringExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRecurringExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecurringExpenseResponse) Reset() {
	*x = DeleteRecurringExpenseResponse{}
	mi := &file_expense_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecurringExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecurringExpenseResponse) ProtoMessage() {}

func (x *DeleteRecurringExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecurringExpenseResponse.ProtoReflect.Descriptor instead.
func (*DeleteRecurringExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRecurringExpenseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RecurringExpense struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Id            string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ColocationId  string                   `protobuf:"bytes,2,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	PaidBy        string                   `protobuf:"bytes,3,opt,name=paid_by,json=paidBy,proto3" json:"paid_by,omitempty"`
	PaidByNom     string                   `protobuf:"bytes,4,opt,name=paid_by_nom,json=paidByNom,proto3" json:"paid_by_nom,omitempty"`
	PaidByPrenom  string                   `protobuf:"bytes,5,opt,name=paid_by_prenom,json=paidByPrenom,proto3" json:"paid_by_prenom,omitempty"`
	CategoryId    string                   `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                   `protobuf:"bytes,7,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Title         string                   `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                  `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Amount        float64                  `protobuf:"fixed64,10,opt,name=amount,proto3" json:"amount,omitempty"`
	SplitType     SplitType                `protobuf:"varint,11,opt,name=split_type,json=splitType,proto3,enum=coloc.SplitType" json:"split_type,omitempty"`
	Recurrence    Recurrence               `protobuf:"varint,12,opt,name=recurrence,proto3,enum=coloc.Recurrence" json:"recurrence,omitempty"`
	NextDueDate   string                   `protobuf:"bytes,13,opt,name=next_due_date,json=nextDueDate,proto3" json:"next_due_date,omitempty"`
	EndDate       *string                  `protobuf:"bytes,14,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	IsActive      bool                     `protobuf:"varint,15,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                   `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Splits        []*RecurringExpenseSplit `protobuf:"bytes,17,rep,name=splits,proto3" json:"splits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecurringExpense) Reset() {
	*x = RecurringExpense{}
	mi := &file_expense_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecurringExpense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecurringExpense) ProtoMessage() {}

func (x *RecurringExpense) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecurringExpense.ProtoReflect.Descriptor instead.
func (*RecurringExpense) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{16}
}

func (x *RecurringExpense) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecurringExpense) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *RecurringExpense) GetPaidBy() string {
	if x != nil {
		return x.PaidBy
	}
	return ""
}

func (x *RecurringExpense) GetPaidByNom() string {
	if x != nil {
		return x.PaidByNom
	}
	return ""
}

func (x *RecurringExpense) GetPaidByPrenom() string {
	if x != nil {
		return x.PaidByPrenom
	}
	return ""
}

func (x *RecurringExpense) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *RecurringExpense) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *RecurringExpense) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecurringExpense) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RecurringExpense) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RecurringExpense) GetSplitType() SplitType {
	if x != nil {
		return x.SplitType
	}
	return SplitType_SPLIT_TYPE_UNSPECIFIED
}

func (x *RecurringExpense) GetRecurrence() Recurrence {
	if x != nil {
		return x.Recurrence
	}
	return Recurrence_RECURRENCE_UNSPECIFIED
}

func (x *RecurringExpense) GetNextDueDate() string {
	if x != nil {
		return x.NextDueDate
	}
	return ""
}

func (x *RecurringExpense) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

func (x *RecurringExpense) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *RecurringExpense) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RecurringExpense) GetSplits() []*RecurringExpenseSplit {
	if x != nil {
		return x.Splits
	}
	return nil
}

type RecurringExpenseSplit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Percentage    float64                `protobuf:"fixed64,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	UserNom       string                 `protobuf:"bytes,3,opt,name=user_nom,json=userNom,proto3" json:"user_nom,omitempty"`
	UserPrenom    string                 `protobuf:"bytes,4,opt,name=user_prenom,json=userPrenom,proto3" json:"user_prenom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecurringExpenseSplit) Reset() {
	*x = RecurringExpenseSplit{}
	mi := &file_expense_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecurringExpenseSplit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecurringExpenseSplit) ProtoMessage() {}

func (x *RecurringExpenseSplit) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecurringExpenseSplit.ProtoReflect.Descriptor instead.
func (*RecurringExpenseSplit) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{17}
}

func (x *RecurringExpenseSplit) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecurringExpenseSplit) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *RecurringExpenseSplit) GetUserNom() string {
	if x != nil {
		return x.UserNom
	}
	return ""
}

func (x *RecurringExpenseSplit) GetUserPrenom() string {
	if x != nil {
		return x.UserPrenom
	}
	return ""
}

type GetForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	MonthsAhead   int32                  `protobuf:"varint,2,opt,name=months_ahead,json=monthsAhead,proto3" json:"months_ahead,omitempty"` // Number of months to forecast (default 3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_expense_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{18}
}

func (x *GetForecastRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetForecastRequest) GetMonthsAhead() int32 {
	if x != nil {
		return x.MonthsAhead
	}
	return 0
}

type GetForecastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forecasts     []*MonthlyForecast     `protobuf:"bytes,1,rep,name=forecasts,proto3" json:"forecasts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastResponse) Reset() {
	*x = GetForecastResponse{}
	mi := &file_expense_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastResponse) ProtoMessage() {}

func (x *GetForecastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastResponse.ProtoReflect.Descriptor instead.
func (*GetForecastResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{19}
}

func (x *GetForecastResponse) GetForecasts() []*MonthlyForecast {
	if x != nil {
		return x.Forecasts
	}
	return nil
}

type MonthlyForecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // Format: YYYY-MM
	TotalAmount   float64                `protobuf:"fixed64,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Categories    []*CategoryForecast    `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyForecast) Reset() {
	*x = MonthlyForecast{}
	mi := &file_expense_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyForecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyForecast) ProtoMessage() {}

func (x *MonthlyForecast) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyForecast.ProtoReflect.Descriptor instead.
func (*MonthlyForecast) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{20}
}

func (x *MonthlyForecast) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyForecast) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *MonthlyForecast) GetCategories() []*CategoryForecast {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategoryForecast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryForecast) Reset() {
	*x = CategoryForecast{}
	mi := &file_expense_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryForecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryForecast) ProtoMessage() {}

func (x *CategoryForecast) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryForecast.ProtoReflect.Descriptor instead.
func (*CategoryForecast) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{21}
}

func (x *CategoryForecast) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryForecast) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryForecast) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_expense_proto protoreflect.FileDescriptor

const file_expense_proto_rawDesc = "" +
	"\n" +
	"\rexpense.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\"\xba\x01\n" +
	"\fExpenseSplit\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\x12\x1d\n" +
	"\n" +
	"is_settled\x18\x04 \x01(\bR\tisSettled\x12\x19\n" +
	"\buser_nom\x18\x05 \x01(\tR\auserNom\x12\x1f\n" +
	"\vuser_prenom\x18\x06 \x01(\tR\n" +
	"userPrenom\"\xc7\x02\n" +
	"\x14CreateExpenseRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12/\n" +
	"\n" +
	"split_type\x18\x06 \x01(\x0e2\x10.coloc.SplitTypeR\tsplitType\x120\n" +
	"\x06splits\x18\a \x03(\v2\x18.coloc.ExpenseSplitInputR\x06splits\x12!\n" +
	"\fexpense_date\x18\b \x01(\tR\vexpenseDateB\x0e\n" +
	"\f_description\"d\n" +
	"\x11ExpenseSplitInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"H\n" +
	"\x11GetExpenseRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xcc\x02\n" +
	"\x13ListExpensesRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12\x1c\n" +
	"\apaid_by\x18\x03 \x01(\tH\x01R\x06paidBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tH\x02R\tstartDate\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\x05 \x01(\tH\x03R\aendDate\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x06 \x01(\x05H\x04R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\a \x01(\x05H\x05R\bpageSize\x88\x01\x01B\x0e\n" +
	"\f_category_idB\n" +
	"\n" +
	"\b_paid_byB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_dateB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\x94\x01\n" +
	"\x14ListExpensesResponse\x12*\n" +
	"\bexpenses\x18\x01 \x03(\v2\x0e.coloc.ExpenseR\bexpenses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb5\x03\n" +
	"\x14UpdateExpenseRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x05 \x01(\x01H\x02R\x06amount\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x06 \x01(\tH\x03R\n" +
	"categoryId\x88\x01\x01\x124\n" +
	"\n" +
	"split_type\x18\a \x01(\x0e2\x10.coloc.SplitTypeH\x04R\tsplitType\x88\x01\x01\x120\n" +
	"\x06splits\x18\b \x03(\v2\x18.coloc.ExpenseSplitInputR\x06splits\x12&\n" +
	"\fexpense_date\x18\t \x01(\tH\x05R\vexpenseDate\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_amountB\x0e\n" +
	"\f_category_idB\r\n" +
	"\v_split_typeB\x0f\n" +
	"\r_expense_date\"K\n" +
	"\x14DeleteExpenseRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"1\n" +
	"\x15DeleteExpenseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa1\x04\n" +
	"\aExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcolocation_id\x18\x02 \x01(\tR\fcolocationId\x12\x17\n" +
	"\apaid_by\x18\x03 \x01(\tR\x06paidBy\x12\x1e\n" +
	"\vpaid_by_nom\x18\x04 \x01(\tR\tpaidByNom\x12$\n" +
	"\x0epaid_by_prenom\x18\x05 \x01(\tR\fpaidByPrenom\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\a \x01(\tR\fcategoryName\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x01R\x06amount\x12/\n" +
	"\n" +
	"split_type\x18\v \x01(\x0e2\x10.coloc.SplitTypeR\tsplitType\x12!\n" +
	"\fexpense_date\x18\f \x01(\tR\vexpenseDate\x12&\n" +
	"\frecurring_id\x18\r \x01(\tH\x01R\vrecurringId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12+\n" +
	"\x06splits\x18\x0f \x03(\v2\x13.coloc.ExpenseSplitR\x06splitsB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_recurring_id\"\xac\x03\n" +
	"\x1dCreateRecurringExpenseRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12/\n" +
	"\n" +
	"split_type\x18\x06 \x01(\x0e2\x10.coloc.SplitTypeR\tsplitType\x120\n" +
	"\x06splits\x18\a \x03(\v2\x18.coloc.ExpenseSplitInputR\x06splits\x121\n" +
	"\n" +
	"recurrence\x18\b \x01(\x0e2\x11.coloc.RecurrenceR\n" +
	"recurrence\x12\x1d\n" +
	"\n" +
	"start_date\x18\t \x01(\tR\tstartDate\x12\x1e\n" +
	"\bend_date\x18\n" +
	" \x01(\tH\x01R\aendDate\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_end_date\"C\n" +
	"\x1cListRecurringExpensesRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\"g\n" +
	"\x1dListRecurringExpensesResponse\x12F\n" +
	"\x12recurring_expenses\x18\x01 \x03(\v2\x17.coloc.RecurringExpenseR\x11recurringExpenses\"\xa9\x04\n" +
	"\x1dUpdateRecurringExpenseRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x05 \x01(\x01H\x02R\x06amount\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x06 \x01(\tH\x03R\n" +
	"categoryId\x88\x01\x01\x124\n" +
	"\n" +
	"split_type\x18\a \x01(\x0e2\x10.coloc.SplitTypeH\x04R\tsplitType\x88\x01\x01\x120\n" +
	"\x06splits\x18\b \x03(\v2\x18.coloc.ExpenseSplitInputR\x06splits\x126\n" +
	"\n" +
	"recurrence\x18\t \x01(\x0e2\x11.coloc.RecurrenceH\x05R\n" +
	"recurrence\x88\x01\x01\x12\x1e\n" +
	"\bend_date\x18\n" +
	" \x01(\tH\x06R\aendDate\x88\x01\x01\x12 \n" +
	"\tis_active\x18\v \x01(\bH\aR\bisActive\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_amountB\x0e\n" +
	"\f_category_idB\r\n" +
	"\v_split_typeB\r\n" +
	"\v_recurrenceB\v\n" +
	"\t_end_dateB\f\n" +
	"\n" +
	"_is_active\"T\n" +
	"\x1dDeleteRecurringExpenseRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\":\n" +
	"\x1eDeleteRecurringExpenseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xf8\x04\n" +
	"\x10RecurringExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcolocation_id\x18\x02 \x01(\tR\fcolocationId\x12\x17\n" +
	"\apaid_by\x18\x03 \x01(\tR\x06paidBy\x12\x1e\n" +
	"\vpaid_by_nom\x18\x04 \x01(\tR\tpaidByNom\x12$\n" +
	"\x0epaid_by_prenom\x18\x05 \x01(\tR\fpaidByPrenom\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\a \x01(\tR\fcategoryName\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\t \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x01R\x06amount\x12/\n" +
	"\n" +
	"split_type\x18\v \x01(\x0e2\x10.coloc.SplitTypeR\tsplitType\x121\n" +
	"\n" +
	"recurrence\x18\f \x01(\x0e2\x11.coloc.RecurrenceR\n" +
	"recurrence\x12\"\n" +
	"\rnext_due_date\x18\r \x01(\tR\vnextDueDate\x12\x1e\n" +
	"\bend_date\x18\x0e \x01(\tH\x01R\aendDate\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\x0f \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x124\n" +
	"\x06splits\x18\x11 \x03(\v2\x1c.coloc.RecurringExpenseSplitR\x06splitsB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_end_date\"\x8c\x01\n" +
	"\x15RecurringExpenseSplit\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"percentage\x18\x02 \x01(\x01R\n" +
	"percentage\x12\x19\n" +
	"\buser_nom\x18\x03 \x01(\tR\auserNom\x12\x1f\n" +
	"\vuser_prenom\x18\x04 \x01(\tR\n" +
	"userPrenom\"\\\n" +
	"\x12GetForecastRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12!\n" +
	"\fmonths_ahead\x18\x02 \x01(\x05R\vmonthsAhead\"K\n" +
	"\x13GetForecastResponse\x124\n" +
	"\tforecasts\x18\x01 \x03(\v2\x16.coloc.MonthlyForecastR\tforecasts\"\x83\x01\n" +
	"\x0fMonthlyForecast\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x01R\vtotalAmount\x127\n" +
	"\n" +
	"categories\x18\x03 \x03(\v2\x17.coloc.CategoryForecastR\n" +
	"categories\"p\n" +
	"\x10CategoryForecast\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount*o\n" +
	"\tSplitType\x12\x1a\n" +
	"\x16SPLIT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SPLIT_TYPE_EQUAL\x10\x01\x12\x19\n" +
	"\x15SPLIT_TYPE_PERCENTAGE\x10\x02\x12\x15\n" +
	"\x11SPLIT_TYPE_CUSTOM\x10\x03*\x84\x01\n" +
	"\n" +
	"Recurrence\x12\x1a\n" +
	"\x16RECURRENCE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10RECURRENCE_DAILY\x10\x01\x12\x15\n" +
	"\x11RECURRENCE_WEEKLY\x10\x02\x12\x16\n" +
	"\x12RECURRENCE_MONTHLY\x10\x03\x12\x15\n" +
	"\x11RECURRENCE_YEARLY\x10\x042\xf6\n" +
	"\n" +
	"\x0eExpenseService\x12r\n" +
	"\rCreateExpense\x12\x1b.coloc.CreateExpenseRequest\x1a\x0e.coloc.Expense\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/colocations/{colocation_id}/expenses\x12n\n" +
	"\n" +
	"GetExpense\x12\x18.coloc.GetExpenseRequest\x1a\x0e.coloc.Expense\"6\x82\xd3\xe4\x93\x020\x12./api/colocations/{colocation_id}/expenses/{id}\x12z\n" +
	"\fListExpenses\x12\x1a.coloc.ListExpensesRequest\x1a\x1b.coloc.ListExpensesResponse\"1\x82\xd3\xe4\x93\x02+\x12)/api/colocations/{colocation_id}/expenses\x12w\n" +
	"\rUpdateExpense\x12\x1b.coloc.UpdateExpenseRequest\x1a\x0e.coloc.Expense\"9\x82\xd3\xe4\x93\x023:\x01*\x1a./api/colocations/{colocation_id}/expenses/{id}\x12\x82\x01\n" +
	"\rDeleteExpense\x12\x1b.coloc.DeleteExpenseRequest\x1a\x1c.coloc.DeleteExpenseResponse\"6\x82\xd3\xe4\x93\x020*./api/colocations/{colocation_id}/expenses/{id}\x12\x97\x01\n" +
	"\x16CreateRecurringExpense\x12$.coloc.CreateRecurringExpenseRequest\x1a\x17.coloc.RecurringExpense\">\x82\xd3\xe4\x93\x028:\x01*\"3/api/colocations/{colocation_id}/recurring-expenses\x12\x9f\x01\n" +
	"\x15ListRecurringExpenses\x12#.coloc.ListRecurringExpensesRequest\x1a$.coloc.ListRecurringExpensesResponse\";\x82\xd3\xe4\x93\x025\x123/api/colocations/{colocation_id}/recurring-expenses\x12\x9c\x01\n" +
	"\x16UpdateRecurringExpense\x12$.coloc.UpdateRecurringExpenseRequest\x1a\x17.coloc.RecurringExpense\"C\x82\xd3\xe4\x93\x02=:\x01*\x1a8/api/colocations/{colocation_id}/recurring-expenses/{id}\x12\xa7\x01\n" +
	"\x16DeleteRecurringExpense\x12$.coloc.DeleteRecurringExpenseRequest\x1a%.coloc.DeleteRecurringExpenseResponse\"@\x82\xd3\xe4\x93\x02:*8/api/colocations/{colocation_id}/recurring-expenses/{id}\x12\x80\x01\n" +
	"\vGetForecast\x12\x19.coloc.GetForecastRequest\x1a\x1a.coloc.GetForecastResponse\":\x82\xd3\xe4\x93\x024\x122/api/colocations/{colocation_id}/expenses/forecastB,Z*github.com/vblanchet22/back_coloc/proto/pbb\x06proto3"

var (
	file_expense_proto_rawDescOnce sync.Once
	file_expense_proto_rawDescData []byte
)

func file_expense_proto_rawDescGZIP() []byte {
	file_expense_proto_rawDescOnce.Do(func() {
		file_expense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)))
	})
	return file_expense_proto_rawDescData
}

var file_expense_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_expense_proto_goTypes = []any{
	(SplitType)(0),                         // 0: coloc.SplitType
	(Recurrence)(0),                        // 1: coloc.Recurrence
	(*ExpenseSplit)(nil),                   // 2: coloc.ExpenseSplit
	(*CreateExpenseRequest)(nil),           // 3: coloc.CreateExpenseRequest
	(*ExpenseSplitInput)(nil),              // 4: coloc.ExpenseSplitInput
	(*GetExpenseRequest)(nil),              // 5: coloc.GetExpenseRequest
	(*ListExpensesRequest)(nil),            // 6: coloc.ListExpensesRequest
	(*ListExpensesResponse)(nil),           // 7: coloc.ListExpensesResponse
	(*UpdateExpenseRequest)(nil),           // 8: coloc.UpdateExpenseRequest
	(*DeleteExpenseRequest)(nil),           // 9: coloc.DeleteExpenseRequest
	(*DeleteExpenseResponse)(nil),          // 10: coloc.DeleteExpenseResponse
	(*Expense)(nil),                        // 11: coloc.Expense
	(*CreateRecurringExpenseRequest)(nil),  // 12: coloc.CreateRecurringExpenseRequest
	(*ListRecurringExpensesRequest)(nil),   // 13: coloc.ListRecurringExpensesRequest
	(*ListRecurringExpensesResponse)(nil),  // 14: coloc.ListRecurringExpensesResponse
	(*UpdateRecurringExpenseRequest)(nil),  // 15: coloc.UpdateRecurringExpenseRequest
	(*DeleteRecurringExpenseRequest)(nil),  // 16: coloc.DeleteRecurringExpenseRequest
	(*DeleteRecurringExpenseResponse)(nil), // 17: coloc.DeleteRecurringExpenseResponse
	(*RecurringExpense)(nil),               // 18: coloc.RecurringExpense
	(*RecurringExpenseSplit)(nil),          // 19: coloc.RecurringExpenseSplit
	(*GetForecastRequest)(nil),             // 20: coloc.GetForecastRequest
	(*GetForecastResponse)(nil),            // 21: coloc.GetForecastResponse
	(*MonthlyForecast)(nil),                // 22: coloc.MonthlyForecast
	(*CategoryForecast)(nil),               // 23: coloc.CategoryForecast
}
var file_expense_proto_depIdxs = []int32{
	0,  // 0: coloc.CreateExpenseRequest.split_type:type_name -> coloc.SplitType
	4,  // 1: coloc.CreateExpenseRequest.splits:type_name -> coloc.ExpenseSplitInput
	11, // 2: coloc.ListExpensesResponse.expenses:type_name -> coloc.Expense
	0,  // 3: coloc.UpdateExpenseRequest.split_type:type_name -> coloc.SplitType
	4,  // 4: coloc.UpdateExpenseRequest.splits:type_name -> coloc.ExpenseSplitInput
	0,  // 5: coloc.Expense.split_type:type_name -> coloc.SplitType
	2,  // 6: coloc.Expense.splits:type_name -> coloc.ExpenseSplit
	0,  // 7: coloc.CreateRecurringExpenseRequest.split_type:type_name -> coloc.SplitType
	4,  // 8: coloc.CreateRecurringExpenseRequest.splits:type_name -> coloc.ExpenseSplitInput
	1,  // 9: coloc.CreateRecurringExpenseRequest.recurrence:type_name -> coloc.Recurrence
	18, // 10: coloc.ListRecurringExpensesResponse.recurring_expenses:type_name -> coloc.RecurringExpense
	0,  // 11: coloc.UpdateRecurringExpenseRequest.split_type:type_name -> coloc.SplitType
	4,  // 12: coloc.UpdateRecurringExpenseRequest.splits:type_name -> coloc.ExpenseSplitInput
	1,  // 13: coloc.UpdateRecurringExpenseRequest.recurrence:type_name -> coloc.Recurrence
	0,  // 14: coloc.RecurringExpense.split_type:type_name -> coloc.SplitType
	1,  // 15: coloc.RecurringExpense.recurrence:type_name -> coloc.Recurrence
	19, // 16: coloc.RecurringExpense.splits:type_name -> coloc.RecurringExpenseSplit
	22, // 17: coloc.GetForecastResponse.forecasts:type_name -> coloc.MonthlyForecast
	23, // 18: coloc.MonthlyForecast.categories:type_name -> coloc.CategoryForecast
	3,  // 19: coloc.ExpenseService.CreateExpense:input_type -> coloc.CreateExpenseRequest
	5,  // 20: coloc.ExpenseService.GetExpense:input_type -> coloc.GetExpenseRequest
	6,  // 21: coloc.ExpenseService.ListExpenses:input_type -> coloc.ListExpensesRequest
	8,  // 22: coloc.ExpenseService.UpdateExpense:input_type -> coloc.UpdateExpenseRequest
	9,  // 23: coloc.ExpenseService.DeleteExpense:input_type -> coloc.DeleteExpenseRequest
	12, // 24: coloc.ExpenseService.CreateRecurringExpense:input_type -> coloc.CreateRecurringExpenseRequest
	13, // 25: coloc.ExpenseService.ListRecurringExpenses:input_type -> coloc.ListRecurringExpensesRequest
	15, // 26: coloc.ExpenseService.UpdateRecurringExpense:input_type -> coloc.UpdateRecurringExpenseRequest
	16, // 27: coloc.ExpenseService.DeleteRecurringExpense:input_type -> coloc.DeleteRecurringExpenseRequest
	20, // 28: coloc.ExpenseService.GetForecast:input_type -> coloc.GetForecastRequest
	11, // 29: coloc.ExpenseService.CreateExpense:output_type -> coloc.Expense
	11, // 30: coloc.ExpenseService.GetExpense:output_type -> coloc.Expense
	7,  // 31: coloc.ExpenseService.ListExpenses:output_type -> coloc.ListExpensesResponse
	11, // 32: coloc.ExpenseService.UpdateExpense:output_type -> coloc.Expense
	10, // 33: coloc.ExpenseService.DeleteExpense:output_type -> coloc.DeleteExpenseResponse
	18, // 34: coloc.ExpenseService.CreateRecurringExpense:output_type -> coloc.RecurringExpense
	14, // 35: coloc.ExpenseService.ListRecurringExpenses:output_type -> coloc.ListRecurringExpensesResponse
	18, // 36: coloc.ExpenseService.UpdateRecurringExpense:output_type -> coloc.RecurringExpense
	17, // 37: coloc.ExpenseService.DeleteRecurringExpense:output_type -> coloc.DeleteRecurringExpenseResponse
	21, // 38: coloc.ExpenseService.GetForecast:output_type -> coloc.GetForecastResponse
	29, // [29:39] is the sub-list for method output_type
	19, // [19:29] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_expense_proto_init() }
func file_expense_proto_init() {
	if File_expense_proto != nil {
		return
	}
	file_expense_proto_msgTypes[1].OneofWrappers = []any{}
	file_expense_proto_msgTypes[4].OneofWrappers = []any{}
	file_expense_proto_msgTypes[6].OneofWrappers = []any{}
	file_expense_proto_msgTypes[9].OneofWrappers = []any{}
	file_expense_proto_msgTypes[10].OneofWrappers = []any{}
	file_expense_proto_msgTypes[13].OneofWrappers = []any{}
	file_expense_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expense_proto_goTypes,
		DependencyIndexes: file_expense_proto_depIdxs,
		EnumInfos:         file_expense_proto_enumTypes,
		MessageInfos:      file_expense_proto_msgTypes,
	}.Build()
	File_expense_proto = out.File
	file_expense_proto_goTypes = nil
	file_expense_proto_depIdxs = nil
}
