// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: fund.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FundService_CreateFund_FullMethodName         = "/coloc.FundService/CreateFund"
	FundService_GetFund_FullMethodName            = "/coloc.FundService/GetFund"
	FundService_ListFunds_FullMethodName          = "/coloc.FundService/ListFunds"
	FundService_UpdateFund_FullMethodName         = "/coloc.FundService/UpdateFund"
	FundService_DeleteFund_FullMethodName         = "/coloc.FundService/DeleteFund"
	FundService_AddContribution_FullMethodName    = "/coloc.FundService/AddContribution"
	FundService_ListContributions_FullMethodName  = "/coloc.FundService/ListContributions"
	FundService_DeleteContribution_FullMethodName = "/coloc.FundService/DeleteContribution"
)

// FundServiceClient is the client API for FundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FundService handles common fund operations
type FundServiceClient interface {
	// Create a new common fund
	CreateFund(ctx context.Context, in *CreateFundRequest, opts ...grpc.CallOption) (*Fund, error)
	// Get fund by ID
	GetFund(ctx context.Context, in *GetFundRequest, opts ...grpc.CallOption) (*Fund, error)
	// List funds for colocation
	ListFunds(ctx context.Context, in *ListFundsRequest, opts ...grpc.CallOption) (*ListFundsResponse, error)
	// Update fund
	UpdateFund(ctx context.Context, in *UpdateFundRequest, opts ...grpc.CallOption) (*Fund, error)
	// Delete fund
	DeleteFund(ctx context.Context, in *DeleteFundRequest, opts ...grpc.CallOption) (*DeleteFundResponse, error)
	// Add contribution to fund
	AddContribution(ctx context.Context, in *AddContributionRequest, opts ...grpc.CallOption) (*Contribution, error)
	// List contributions for fund
	ListContributions(ctx context.Context, in *ListContributionsRequest, opts ...grpc.CallOption) (*ListContributionsResponse, error)
	// Delete contribution
	DeleteContribution(ctx context.Context, in *DeleteContributionRequest, opts ...grpc.CallOption) (*DeleteContributionResponse, error)
}

type fundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFundServiceClient(cc grpc.ClientConnInterface) FundServiceClient {
	return &fundServiceClient{cc}
}

func (c *fundServiceClient) CreateFund(ctx context.Context, in *CreateFundRequest, opts ...grpc.CallOption) (*Fund, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fund)
	err := c.cc.Invoke(ctx, FundService_CreateFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) GetFund(ctx context.Context, in *GetFundRequest, opts ...grpc.CallOption) (*Fund, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fund)
	err := c.cc.Invoke(ctx, FundService_GetFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) ListFunds(ctx context.Context, in *ListFundsRequest, opts ...grpc.CallOption) (*ListFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFundsResponse)
	err := c.cc.Invoke(ctx, FundService_ListFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) UpdateFund(ctx context.Context, in *UpdateFundRequest, opts ...grpc.CallOption) (*Fund, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Fund)
	err := c.cc.Invoke(ctx, FundService_UpdateFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) DeleteFund(ctx context.Context, in *DeleteFundRequest, opts ...grpc.CallOption) (*DeleteFundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFundResponse)
	err := c.cc.Invoke(ctx, FundService_DeleteFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) AddContribution(ctx context.Context, in *AddContributionRequest, opts ...grpc.CallOption) (*Contribution, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Contribution)
	err := c.cc.Invoke(ctx, FundService_AddContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) ListContributions(ctx context.Context, in *ListContributionsRequest, opts ...grpc.CallOption) (*ListContributionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContributionsResponse)
	err := c.cc.Invoke(ctx, FundService_ListContributions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) DeleteContribution(ctx context.Context, in *DeleteContributionRequest, opts ...grpc.CallOption) (*DeleteContributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteContributionResponse)
	err := c.cc.Invoke(ctx, FundService_DeleteContribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundServiceServer is the server API for FundService service.
// All implementations must embed UnimplementedFundServiceServer
// for forward compatibility.
//
// FundService handles common fund operations
type FundServiceServer interface {
	// Create a new common fund
	CreateFund(context.Context, *CreateFundRequest) (*Fund, error)
	// Get fund by ID
	GetFund(context.Context, *GetFundRequest) (*Fund, error)
	// List funds for colocation
	ListFunds(context.Context, *ListFundsRequest) (*ListFundsResponse, error)
	// Update fund
	UpdateFund(context.Context, *UpdateFundRequest) (*Fund, error)
	// Delete fund
	DeleteFund(context.Context, *DeleteFundRequest) (*DeleteFundResponse, error)
	// Add contribution to fund
	AddContribution(context.Context, *AddContributionRequest) (*Contribution, error)
	// List contributions for fund
	ListContributions(context.Context, *ListContributionsRequest) (*ListContributionsResponse, error)
	// Delete contribution
	DeleteContribution(context.Context, *DeleteContributionRequest) (*DeleteContributionResponse, error)
	mustEmbedUnimplementedFundServiceServer()
}

// UnimplementedFundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFundServiceServer struct{}

func (UnimplementedFundServiceServer) CreateFund(context.Context, *CreateFundRequest) (*Fund, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFund not implemented")
}
func (UnimplementedFundServiceServer) GetFund(context.Context, *GetFundRequest) (*Fund, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFund not implemented")
}
func (UnimplementedFundServiceServer) ListFunds(context.Context, *ListFundsRequest) (*ListFundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFunds not implemented")
}
func (UnimplementedFundServiceServer) UpdateFund(context.Context, *UpdateFundRequest) (*Fund, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFund not implemented")
}
func (UnimplementedFundServiceServer) DeleteFund(context.Context, *DeleteFundRequest) (*DeleteFundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFund not implemented")
}
func (UnimplementedFundServiceServer) AddContribution(context.Context, *AddContributionRequest) (*Contribution, error) {
	return nil, status.Error(codes.Unimplemented, "method AddContribution not implemented")
}
func (UnimplementedFundServiceServer) ListContributions(context.Context, *ListContributionsRequest) (*ListContributionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContributions not implemented")
}
func (UnimplementedFundServiceServer) DeleteContribution(context.Context, *DeleteContributionRequest) (*DeleteContributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteContribution not implemented")
}
func (UnimplementedFundServiceServer) mustEmbedUnimplementedFundServiceServer() {}
func (UnimplementedFundServiceServer) testEmbeddedByValue()                     {}

// UnsafeFundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FundServiceServer will
// result in compilation errors.
type UnsafeFundServiceServer interface {
	mustEmbedUnimplementedFundServiceServer()
}

func RegisterFundServiceServer(s grpc.ServiceRegistrar, srv FundServiceServer) {
	// If the following call panics, it indicates UnimplementedFundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FundService_ServiceDesc, srv)
}

func _FundService_CreateFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).CreateFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_CreateFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).CreateFund(ctx, req.(*CreateFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_GetFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).GetFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_GetFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).GetFund(ctx, req.(*GetFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_ListFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).ListFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_ListFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).ListFunds(ctx, req.(*ListFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_UpdateFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).UpdateFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_UpdateFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).UpdateFund(ctx, req.(*UpdateFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_DeleteFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).DeleteFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_DeleteFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).DeleteFund(ctx, req.(*DeleteFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_AddContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).AddContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_AddContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).AddContribution(ctx, req.(*AddContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_ListContributions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContributionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).ListContributions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_ListContributions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).ListContributions(ctx, req.(*ListContributionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_DeleteContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).DeleteContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_DeleteContribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).DeleteContribution(ctx, req.(*DeleteContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FundService_ServiceDesc is the grpc.ServiceDesc for FundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coloc.FundService",
	HandlerType: (*FundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFund",
			Handler:    _FundService_CreateFund_Handler,
		},
		{
			MethodName: "GetFund",
			Handler:    _FundService_GetFund_Handler,
		},
		{
			MethodName: "ListFunds",
			Handler:    _FundService_ListFunds_Handler,
		},
		{
			MethodName: "UpdateFund",
			Handler:    _FundService_UpdateFund_Handler,
		},
		{
			MethodName: "DeleteFund",
			Handler:    _FundService_DeleteFund_Handler,
		},
		{
			MethodName: "AddContribution",
			Handler:    _FundService_AddContribution_Handler,
		},
		{
			MethodName: "ListContributions",
			Handler:    _FundService_ListContributions_Handler,
		},
		{
			MethodName: "DeleteContribution",
			Handler:    _FundService_DeleteContribution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fund.proto",
}
