// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notification.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	// Expense notifications
	NotificationType_NOTIFICATION_TYPE_EXPENSE_CREATED NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_EXPENSE_UPDATED NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_EXPENSE_DELETED NotificationType = 3
	// Payment notifications
	NotificationType_NOTIFICATION_TYPE_PAYMENT_RECEIVED  NotificationType = 10
	NotificationType_NOTIFICATION_TYPE_PAYMENT_CONFIRMED NotificationType = 11
	NotificationType_NOTIFICATION_TYPE_PAYMENT_REJECTED  NotificationType = 12
	// Colocation notifications
	NotificationType_NOTIFICATION_TYPE_MEMBER_JOINED       NotificationType = 20
	NotificationType_NOTIFICATION_TYPE_MEMBER_LEFT         NotificationType = 21
	NotificationType_NOTIFICATION_TYPE_MEMBER_REMOVED      NotificationType = 22
	NotificationType_NOTIFICATION_TYPE_INVITATION_RECEIVED NotificationType = 23
	NotificationType_NOTIFICATION_TYPE_ROLE_CHANGED        NotificationType = 24
	// Decision notifications
	NotificationType_NOTIFICATION_TYPE_DECISION_CREATED  NotificationType = 30
	NotificationType_NOTIFICATION_TYPE_DECISION_CLOSED   NotificationType = 31
	NotificationType_NOTIFICATION_TYPE_DECISION_DEADLINE NotificationType = 32
	// Fund notifications
	NotificationType_NOTIFICATION_TYPE_FUND_CREATED      NotificationType = 40
	NotificationType_NOTIFICATION_TYPE_FUND_CONTRIBUTION NotificationType = 41
	NotificationType_NOTIFICATION_TYPE_FUND_GOAL_REACHED NotificationType = 42
	// Event notifications
	NotificationType_NOTIFICATION_TYPE_EVENT_CREATED   NotificationType = 50
	NotificationType_NOTIFICATION_TYPE_EVENT_UPDATED   NotificationType = 51
	NotificationType_NOTIFICATION_TYPE_EVENT_REMINDER  NotificationType = 52
	NotificationType_NOTIFICATION_TYPE_EVENT_CANCELLED NotificationType = 53
	// Recurring expense notifications
	NotificationType_NOTIFICATION_TYPE_RECURRING_DUE NotificationType = 60
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0:  "NOTIFICATION_TYPE_UNSPECIFIED",
		1:  "NOTIFICATION_TYPE_EXPENSE_CREATED",
		2:  "NOTIFICATION_TYPE_EXPENSE_UPDATED",
		3:  "NOTIFICATION_TYPE_EXPENSE_DELETED",
		10: "NOTIFICATION_TYPE_PAYMENT_RECEIVED",
		11: "NOTIFICATION_TYPE_PAYMENT_CONFIRMED",
		12: "NOTIFICATION_TYPE_PAYMENT_REJECTED",
		20: "NOTIFICATION_TYPE_MEMBER_JOINED",
		21: "NOTIFICATION_TYPE_MEMBER_LEFT",
		22: "NOTIFICATION_TYPE_MEMBER_REMOVED",
		23: "NOTIFICATION_TYPE_INVITATION_RECEIVED",
		24: "NOTIFICATION_TYPE_ROLE_CHANGED",
		30: "NOTIFICATION_TYPE_DECISION_CREATED",
		31: "NOTIFICATION_TYPE_DECISION_CLOSED",
		32: "NOTIFICATION_TYPE_DECISION_DEADLINE",
		40: "NOTIFICATION_TYPE_FUND_CREATED",
		41: "NOTIFICATION_TYPE_FUND_CONTRIBUTION",
		42: "NOTIFICATION_TYPE_FUND_GOAL_REACHED",
		50: "NOTIFICATION_TYPE_EVENT_CREATED",
		51: "NOTIFICATION_TYPE_EVENT_UPDATED",
		52: "NOTIFICATION_TYPE_EVENT_REMINDER",
		53: "NOTIFICATION_TYPE_EVENT_CANCELLED",
		60: "NOTIFICATION_TYPE_RECURRING_DUE",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":         0,
		"NOTIFICATION_TYPE_EXPENSE_CREATED":     1,
		"NOTIFICATION_TYPE_EXPENSE_UPDATED":     2,
		"NOTIFICATION_TYPE_EXPENSE_DELETED":     3,
		"NOTIFICATION_TYPE_PAYMENT_RECEIVED":    10,
		"NOTIFICATION_TYPE_PAYMENT_CONFIRMED":   11,
		"NOTIFICATION_TYPE_PAYMENT_REJECTED":    12,
		"NOTIFICATION_TYPE_MEMBER_JOINED":       20,
		"NOTIFICATION_TYPE_MEMBER_LEFT":         21,
		"NOTIFICATION_TYPE_MEMBER_REMOVED":      22,
		"NOTIFICATION_TYPE_INVITATION_RECEIVED": 23,
		"NOTIFICATION_TYPE_ROLE_CHANGED":        24,
		"NOTIFICATION_TYPE_DECISION_CREATED":    30,
		"NOTIFICATION_TYPE_DECISION_CLOSED":     31,
		"NOTIFICATION_TYPE_DECISION_DEADLINE":   32,
		"NOTIFICATION_TYPE_FUND_CREATED":        40,
		"NOTIFICATION_TYPE_FUND_CONTRIBUTION":   41,
		"NOTIFICATION_TYPE_FUND_GOAL_REACHED":   42,
		"NOTIFICATION_TYPE_EVENT_CREATED":       50,
		"NOTIFICATION_TYPE_EVENT_UPDATED":       51,
		"NOTIFICATION_TYPE_EVENT_REMINDER":      52,
		"NOTIFICATION_TYPE_EVENT_CANCELLED":     53,
		"NOTIFICATION_TYPE_RECURRING_DUE":       60,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  *string                `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3,oneof" json:"colocation_id,omitempty"`
	UnreadOnly    *bool                  `protobuf:"varint,2,opt,name=unread_only,json=unreadOnly,proto3,oneof" json:"unread_only,omitempty"`
	Page          *int32                 `protobuf:"varint,3,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotificationsRequest) GetColocationId() string {
	if x != nil && x.ColocationId != nil {
		return *x.ColocationId
	}
	return ""
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil && x.UnreadOnly != nil {
		return *x.UnreadOnly
	}
	return false
}

func (x *ListNotificationsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListNotificationsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	UnreadCount   int32                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListNotificationsResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ListNotificationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MarkAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *MarkAsReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *MarkAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MarkAllAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  *string                `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3,oneof" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadRequest) Reset() {
	*x = MarkAllAsReadRequest{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadRequest) ProtoMessage() {}

func (x *MarkAllAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *MarkAllAsReadRequest) GetColocationId() string {
	if x != nil && x.ColocationId != nil {
		return *x.ColocationId
	}
	return ""
}

type MarkAllAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarkedCount   int32                  `protobuf:"varint,1,opt,name=marked_count,json=markedCount,proto3" json:"marked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadResponse) Reset() {
	*x = MarkAllAsReadResponse{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadResponse) ProtoMessage() {}

func (x *MarkAllAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAllAsReadResponse) GetMarkedCount() int32 {
	if x != nil {
		return x.MarkedCount
	}
	return 0
}

type DeleteNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationResponse) Reset() {
	*x = DeleteNotificationResponse{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationResponse) ProtoMessage() {}

func (x *DeleteNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  *string                `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3,oneof" json:"colocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{8}
}

func (x *GetUnreadCountRequest) GetColocationId() string {
	if x != nil && x.ColocationId != nil {
		return *x.ColocationId
	}
	return ""
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{9}
}

func (x *GetUnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNotificationsRequest) Reset() {
	*x = StreamNotificationsRequest{}
	mi := &file_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationsRequest) ProtoMessage() {}

func (x *StreamNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNotificationsRequest.ProtoReflect.Descriptor instead.
func (*StreamNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{10}
}

type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ColocationId   *string                `protobuf:"bytes,3,opt,name=colocation_id,json=colocationId,proto3,oneof" json:"colocation_id,omitempty"`
	ColocationName *string                `protobuf:"bytes,4,opt,name=colocation_name,json=colocationName,proto3,oneof" json:"colocation_name,omitempty"`
	Type           NotificationType       `protobuf:"varint,5,opt,name=type,proto3,enum=coloc.NotificationType" json:"type,omitempty"`
	Title          string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Data           map[string]string      `protobuf:"bytes,8,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional data (expense_id, payment_id, etc.)
	IsRead         bool                   `protobuf:"varint,9,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{11}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetColocationId() string {
	if x != nil && x.ColocationId != nil {
		return *x.ColocationId
	}
	return ""
}

func (x *Notification) GetColocationName() string {
	if x != nil && x.ColocationName != nil {
		return *x.ColocationName
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\"\xde\x01\n" +
	"\x18ListNotificationsRequest\x12(\n" +
	"\rcolocation_id\x18\x01 \x01(\tH\x00R\fcolocationId\x88\x01\x01\x12$\n" +
	"\vunread_only\x18\x02 \x01(\bH\x01R\n" +
	"unreadOnly\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x03 \x01(\x05H\x02R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05H\x03R\bpageSize\x88\x01\x01B\x10\n" +
	"\x0e_colocation_idB\x0e\n" +
	"\f_unread_onlyB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\xcb\x01\n" +
	"\x19ListNotificationsResponse\x129\n" +
	"\rnotifications\x18\x01 \x03(\v2\x13.coloc.NotificationR\rnotifications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\funread_count\x18\x03 \x01(\x05R\vunreadCount\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"#\n" +
	"\x11MarkAsReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12MarkAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x14MarkAllAsReadRequest\x12(\n" +
	"\rcolocation_id\x18\x01 \x01(\tH\x00R\fcolocationId\x88\x01\x01B\x10\n" +
	"\x0e_colocation_id\":\n" +
	"\x15MarkAllAsReadResponse\x12!\n" +
	"\fmarked_count\x18\x01 \x01(\x05R\vmarkedCount\"+\n" +
	"\x19DeleteNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x1aDeleteNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"S\n" +
	"\x15GetUnreadCountRequest\x12(\n" +
	"\rcolocation_id\x18\x01 \x01(\tH\x00R\fcolocationId\x88\x01\x01B\x10\n" +
	"\x0e_colocation_id\".\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x1c\n" +
	"\x1aStreamNotificationsRequest\"\xb0\x03\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\rcolocation_id\x18\x03 \x01(\tH\x00R\fcolocationId\x88\x01\x01\x12,\n" +
	"\x0fcolocation_name\x18\x04 \x01(\tH\x01R\x0ecolocationName\x88\x01\x01\x12+\n" +
	"\x04type\x18\x05 \x01(\x0e2\x17.coloc.NotificationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x121\n" +
	"\x04data\x18\b \x03(\v2\x1d.coloc.Notification.DataEntryR\x04data\x12\x17\n" +
	"\ais_read\x18\t \x01(\bR\x06isRead\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_colocation_idB\x12\n" +
	"\x10_colocation_name*\x8a\a\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!NOTIFICATION_TYPE_EXPENSE_CREATED\x10\x01\x12%\n" +
	"!NOTIFICATION_TYPE_EXPENSE_UPDATED\x10\x02\x12%\n" +
	"!NOTIFICATION_TYPE_EXPENSE_DELETED\x10\x03\x12&\n" +
	"\"NOTIFICATION_TYPE_PAYMENT_RECEIVED\x10\n" +
	"\x12'\n" +
	"#NOTIFICATION_TYPE_PAYMENT_CONFIRMED\x10\v\x12&\n" +
	"\"NOTIFICATION_TYPE_PAYMENT_REJECTED\x10\f\x12#\n" +
	"\x1fNOTIFICATION_TYPE_MEMBER_JOINED\x10\x14\x12!\n" +
	"\x1dNOTIFICATION_TYPE_MEMBER_LEFT\x10\x15\x12$\n" +
	" NOTIFICATION_TYPE_MEMBER_REMOVED\x10\x16\x12)\n" +
	"%NOTIFICATION_TYPE_INVITATION_RECEIVED\x10\x17\x12\"\n" +
	"\x1eNOTIFICATION_TYPE_ROLE_CHANGED\x10\x18\x12&\n" +
	"\"NOTIFICATION_TYPE_DECISION_CREATED\x10\x1e\x12%\n" +
	"!NOTIFICATION_TYPE_DECISION_CLOSED\x10\x1f\x12'\n" +
	"#NOTIFICATION_TYPE_DECISION_DEADLINE\x10 \x12\"\n" +
	"\x1eNOTIFICATION_TYPE_FUND_CREATED\x10(\x12'\n" +
	"#NOTIFICATION_TYPE_FUND_CONTRIBUTION\x10)\x12'\n" +
	"#NOTIFICATION_TYPE_FUND_GOAL_REACHED\x10*\x12#\n" +
	"\x1fNOTIFICATION_TYPE_EVENT_CREATED\x102\x12#\n" +
	"\x1fNOTIFICATION_TYPE_EVENT_UPDATED\x103\x12$\n" +
	" NOTIFICATION_TYPE_EVENT_REMINDER\x104\x12%\n" +
	"!NOTIFICATION_TYPE_EVENT_CANCELLED\x105\x12#\n" +
	"\x1fNOTIFICATION_TYPE_RECURRING_DUE\x10<2\xae\x05\n" +
	"\x13NotificationService\x12r\n" +
	"\x11ListNotifications\x12\x1f.coloc.ListNotificationsRequest\x1a .coloc.ListNotificationsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/notifications\x12j\n" +
	"\n" +
	"MarkAsRead\x12\x18.coloc.MarkAsReadRequest\x1a\x19.coloc.MarkAsReadResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/notifications/{id}/read\x12r\n" +
	"\rMarkAllAsRead\x12\x1b.coloc.MarkAllAsReadRequest\x1a\x1c.coloc.MarkAllAsReadResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/notifications/read-all\x12z\n" +
	"\x12DeleteNotification\x12 .coloc.DeleteNotificationRequest\x1a!.coloc.DeleteNotificationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/api/notifications/{id}\x12v\n" +
	"\x0eGetUnreadCount\x12\x1c.coloc.GetUnreadCountRequest\x1a\x1d.coloc.GetUnreadCountResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/notifications/unread-count\x12O\n" +
	"\x13StreamNotifications\x12!.coloc.StreamNotificationsRequest\x1a\x13.coloc.Notification0\x01B,Z*github.com/vblanchet22/back_coloc/proto/pbb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_notification_proto_goTypes = []any{
	(NotificationType)(0),              // 0: coloc.NotificationType
	(*ListNotificationsRequest)(nil),   // 1: coloc.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),  // 2: coloc.ListNotificationsResponse
	(*MarkAsReadRequest)(nil),          // 3: coloc.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),         // 4: coloc.MarkAsReadResponse
	(*MarkAllAsReadRequest)(nil),       // 5: coloc.MarkAllAsReadRequest
	(*MarkAllAsReadResponse)(nil),      // 6: coloc.MarkAllAsReadResponse
	(*DeleteNotificationRequest)(nil),  // 7: coloc.DeleteNotificationRequest
	(*DeleteNotificationResponse)(nil), // 8: coloc.DeleteNotificationResponse
	(*GetUnreadCountRequest)(nil),      // 9: coloc.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),     // 10: coloc.GetUnreadCountResponse
	(*StreamNotificationsRequest)(nil), // 11: coloc.StreamNotificationsRequest
	(*Notification)(nil),               // 12: coloc.Notification
	nil,                                // 13: coloc.Notification.DataEntry
}
var file_notification_proto_depIdxs = []int32{
	12, // 0: coloc.ListNotificationsResponse.notifications:type_name -> coloc.Notification
	0,  // 1: coloc.Notification.type:type_name -> coloc.NotificationType
	13, // 2: coloc.Notification.data:type_name -> coloc.Notification.DataEntry
	1,  // 3: coloc.NotificationService.ListNotifications:input_type -> coloc.ListNotificationsRequest
	3,  // 4: coloc.NotificationService.MarkAsRead:input_type -> coloc.MarkAsReadRequest
	5,  // 5: coloc.NotificationService.MarkAllAsRead:input_type -> coloc.MarkAllAsReadRequest
	7,  // 6: coloc.NotificationService.DeleteNotification:input_type -> coloc.DeleteNotificationRequest
	9,  // 7: coloc.NotificationService.GetUnreadCount:input_type -> coloc.GetUnreadCountRequest
	11, // 8: coloc.NotificationService.StreamNotifications:input_type -> coloc.StreamNotificationsRequest
	2,  // 9: coloc.NotificationService.ListNotifications:output_type -> coloc.ListNotificationsResponse
	4,  // 10: coloc.NotificationService.MarkAsRead:output_type -> coloc.MarkAsReadResponse
	6,  // 11: coloc.NotificationService.MarkAllAsRead:output_type -> coloc.MarkAllAsReadResponse
	8,  // 12: coloc.NotificationService.DeleteNotification:output_type -> coloc.DeleteNotificationResponse
	10, // 13: coloc.NotificationService.GetUnreadCount:output_type -> coloc.GetUnreadCountResponse
	12, // 14: coloc.NotificationService.StreamNotifications:output_type -> coloc.Notification
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	file_notification_proto_msgTypes[0].OneofWrappers = []any{}
	file_notification_proto_msgTypes[4].OneofWrappers = []any{}
	file_notification_proto_msgTypes[8].OneofWrappers = []any{}
	file_notification_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
