// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: payment.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_CONFIRMED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_REJECTED    PaymentStatus = 3
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_CONFIRMED",
		3: "PAYMENT_STATUS_REJECTED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_CONFIRMED":   2,
		"PAYMENT_STATUS_REJECTED":    3,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Note          *string                `protobuf:"bytes,4,opt,name=note,proto3,oneof" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CreatePaymentRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *GetPaymentRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Status        *PaymentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=coloc.PaymentStatus,oneof" json:"status,omitempty"`
	FromUserId    *string                `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3,oneof" json:"from_user_id,omitempty"`
	ToUserId      *string                `protobuf:"bytes,4,opt,name=to_user_id,json=toUserId,proto3,oneof" json:"to_user_id,omitempty"`
	Page          *int32                 `protobuf:"varint,5,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *ListPaymentsRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *ListPaymentsRequest) GetStatus() PaymentStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *ListPaymentsRequest) GetFromUserId() string {
	if x != nil && x.FromUserId != nil {
		return *x.FromUserId
	}
	return ""
}

func (x *ListPaymentsRequest) GetToUserId() string {
	if x != nil && x.ToUserId != nil {
		return *x.ToUserId
	}
	return ""
}

func (x *ListPaymentsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListPaymentsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *ListPaymentsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListPaymentsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPaymentsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ConfirmPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmPaymentRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RejectPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Reason        *string                `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectPaymentRequest) Reset() {
	*x = RejectPaymentRequest{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectPaymentRequest) ProtoMessage() {}

func (x *RejectPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectPaymentRequest.ProtoReflect.Descriptor instead.
func (*RejectPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *RejectPaymentRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *RejectPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RejectPaymentRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type CancelPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColocationId  string                 `protobuf:"bytes,1,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *CancelPaymentRequest) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *CancelPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentResponse) Reset() {
	*x = CancelPaymentResponse{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentResponse) ProtoMessage() {}

func (x *CancelPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *CancelPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Payment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ColocationId   string                 `protobuf:"bytes,2,opt,name=colocation_id,json=colocationId,proto3" json:"colocation_id,omitempty"`
	FromUserId     string                 `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromUserNom    string                 `protobuf:"bytes,4,opt,name=from_user_nom,json=fromUserNom,proto3" json:"from_user_nom,omitempty"`
	FromUserPrenom string                 `protobuf:"bytes,5,opt,name=from_user_prenom,json=fromUserPrenom,proto3" json:"from_user_prenom,omitempty"`
	FromAvatarUrl  *string                `protobuf:"bytes,6,opt,name=from_avatar_url,json=fromAvatarUrl,proto3,oneof" json:"from_avatar_url,omitempty"`
	ToUserId       string                 `protobuf:"bytes,7,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	ToUserNom      string                 `protobuf:"bytes,8,opt,name=to_user_nom,json=toUserNom,proto3" json:"to_user_nom,omitempty"`
	ToUserPrenom   string                 `protobuf:"bytes,9,opt,name=to_user_prenom,json=toUserPrenom,proto3" json:"to_user_prenom,omitempty"`
	ToAvatarUrl    *string                `protobuf:"bytes,10,opt,name=to_avatar_url,json=toAvatarUrl,proto3,oneof" json:"to_avatar_url,omitempty"`
	Amount         float64                `protobuf:"fixed64,11,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         PaymentStatus          `protobuf:"varint,12,opt,name=status,proto3,enum=coloc.PaymentStatus" json:"status,omitempty"`
	Note           *string                `protobuf:"bytes,13,opt,name=note,proto3,oneof" json:"note,omitempty"`
	ConfirmedAt    *string                `protobuf:"bytes,14,opt,name=confirmed_at,json=confirmedAt,proto3,oneof" json:"confirmed_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetColocationId() string {
	if x != nil {
		return x.ColocationId
	}
	return ""
}

func (x *Payment) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *Payment) GetFromUserNom() string {
	if x != nil {
		return x.FromUserNom
	}
	return ""
}

func (x *Payment) GetFromUserPrenom() string {
	if x != nil {
		return x.FromUserPrenom
	}
	return ""
}

func (x *Payment) GetFromAvatarUrl() string {
	if x != nil && x.FromAvatarUrl != nil {
		return *x.FromAvatarUrl
	}
	return ""
}

func (x *Payment) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *Payment) GetToUserNom() string {
	if x != nil {
		return x.ToUserNom
	}
	return ""
}

func (x *Payment) GetToUserPrenom() string {
	if x != nil {
		return x.ToUserPrenom
	}
	return ""
}

func (x *Payment) GetToAvatarUrl() string {
	if x != nil && x.ToAvatarUrl != nil {
		return *x.ToAvatarUrl
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *Payment) GetConfirmedAt() string {
	if x != nil && x.ConfirmedAt != nil {
		return *x.ConfirmedAt
	}
	return ""
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\"\x93\x01\n" +
	"\x14CreatePaymentRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x17\n" +
	"\x04note\x18\x04 \x01(\tH\x00R\x04note\x88\x01\x01B\a\n" +
	"\x05_note\"H\n" +
	"\x11GetPaymentRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xb4\x02\n" +
	"\x13ListPaymentsRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.coloc.PaymentStatusH\x00R\x06status\x88\x01\x01\x12%\n" +
	"\ffrom_user_id\x18\x03 \x01(\tH\x01R\n" +
	"fromUserId\x88\x01\x01\x12!\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\tH\x02R\btoUserId\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x05 \x01(\x05H\x03R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x06 \x01(\x05H\x04R\bpageSize\x88\x01\x01B\t\n" +
	"\a_statusB\x0f\n" +
	"\r_from_user_idB\r\n" +
	"\v_to_user_idB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"\x94\x01\n" +
	"\x14ListPaymentsResponse\x12*\n" +
	"\bpayments\x18\x01 \x03(\v2\x0e.coloc.PaymentR\bpayments\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"L\n" +
	"\x15ConfirmPaymentRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"s\n" +
	"\x14RejectPaymentRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"K\n" +
	"\x14CancelPaymentRequest\x12#\n" +
	"\rcolocation_id\x18\x01 \x01(\tR\fcolocationId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"1\n" +
	"\x15CancelPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xce\x04\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rcolocation_id\x18\x02 \x01(\tR\fcolocationId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\tR\n" +
	"fromUserId\x12\"\n" +
	"\rfrom_user_nom\x18\x04 \x01(\tR\vfromUserNom\x12(\n" +
	"\x10from_user_prenom\x18\x05 \x01(\tR\x0efromUserPrenom\x12+\n" +
	"\x0ffrom_avatar_url\x18\x06 \x01(\tH\x00R\rfromAvatarUrl\x88\x01\x01\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\a \x01(\tR\btoUserId\x12\x1e\n" +
	"\vto_user_nom\x18\b \x01(\tR\ttoUserNom\x12$\n" +
	"\x0eto_user_prenom\x18\t \x01(\tR\ftoUserPrenom\x12'\n" +
	"\rto_avatar_url\x18\n" +
	" \x01(\tH\x01R\vtoAvatarUrl\x88\x01\x01\x12\x16\n" +
	"\x06amount\x18\v \x01(\x01R\x06amount\x12,\n" +
	"\x06status\x18\f \x01(\x0e2\x14.coloc.PaymentStatusR\x06status\x12\x17\n" +
	"\x04note\x18\r \x01(\tH\x02R\x04note\x88\x01\x01\x12&\n" +
	"\fconfirmed_at\x18\x0e \x01(\tH\x03R\vconfirmedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAtB\x12\n" +
	"\x10_from_avatar_urlB\x10\n" +
	"\x0e_to_avatar_urlB\a\n" +
	"\x05_noteB\x0f\n" +
	"\r_confirmed_at*\x86\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CONFIRMED\x10\x02\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REJECTED\x10\x032\xf9\x05\n" +
	"\x0ePaymentService\x12r\n" +
	"\rCreatePayment\x12\x1b.coloc.CreatePaymentRequest\x1a\x0e.coloc.Payment\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/colocations/{colocation_id}/payments\x12n\n" +
	"\n" +
	"GetPayment\x12\x18.coloc.GetPaymentRequest\x1a\x0e.coloc.Payment\"6\x82\xd3\xe4\x93\x020\x12./api/colocations/{colocation_id}/payments/{id}\x12z\n" +
	"\fListPayments\x12\x1a.coloc.ListPaymentsRequest\x1a\x1b.coloc.ListPaymentsResponse\"1\x82\xd3\xe4\x93\x02+\x12)/api/colocations/{colocation_id}/payments\x12\x81\x01\n" +
	"\x0eConfirmPayment\x12\x1c.coloc.ConfirmPaymentRequest\x1a\x0e.coloc.Payment\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/api/colocations/{colocation_id}/payments/{id}/confirm\x12~\n" +
	"\rRejectPayment\x12\x1b.coloc.RejectPaymentRequest\x1a\x0e.coloc.Payment\"@\x82\xd3\xe4\x93\x02::\x01*\"5/api/colocations/{colocation_id}/payments/{id}/reject\x12\x82\x01\n" +
	"\rCancelPayment\x12\x1b.coloc.CancelPaymentRequest\x1a\x1c.coloc.CancelPaymentResponse\"6\x82\xd3\xe4\x93\x020*./api/colocations/{colocation_id}/payments/{id}B,Z*github.com/vblanchet22/back_coloc/proto/pbb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_payment_proto_goTypes = []any{
	(PaymentStatus)(0),            // 0: coloc.PaymentStatus
	(*CreatePaymentRequest)(nil),  // 1: coloc.CreatePaymentRequest
	(*GetPaymentRequest)(nil),     // 2: coloc.GetPaymentRequest
	(*ListPaymentsRequest)(nil),   // 3: coloc.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),  // 4: coloc.ListPaymentsResponse
	(*ConfirmPaymentRequest)(nil), // 5: coloc.ConfirmPaymentRequest
	(*RejectPaymentRequest)(nil),  // 6: coloc.RejectPaymentRequest
	(*CancelPaymentRequest)(nil),  // 7: coloc.CancelPaymentRequest
	(*CancelPaymentResponse)(nil), // 8: coloc.CancelPaymentResponse
	(*Payment)(nil),               // 9: coloc.Payment
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: coloc.ListPaymentsRequest.status:type_name -> coloc.PaymentStatus
	9, // 1: coloc.ListPaymentsResponse.payments:type_name -> coloc.Payment
	0, // 2: coloc.Payment.status:type_name -> coloc.PaymentStatus
	1, // 3: coloc.PaymentService.CreatePayment:input_type -> coloc.CreatePaymentRequest
	2, // 4: coloc.PaymentService.GetPayment:input_type -> coloc.GetPaymentRequest
	3, // 5: coloc.PaymentService.ListPayments:input_type -> coloc.ListPaymentsRequest
	5, // 6: coloc.PaymentService.ConfirmPayment:input_type -> coloc.ConfirmPaymentRequest
	6, // 7: coloc.PaymentService.RejectPayment:input_type -> coloc.RejectPaymentRequest
	7, // 8: coloc.PaymentService.CancelPayment:input_type -> coloc.CancelPaymentRequest
	9, // 9: coloc.PaymentService.CreatePayment:output_type -> coloc.Payment
	9, // 10: coloc.PaymentService.GetPayment:output_type -> coloc.Payment
	4, // 11: coloc.PaymentService.ListPayments:output_type -> coloc.ListPaymentsResponse
	9, // 12: coloc.PaymentService.ConfirmPayment:output_type -> coloc.Payment
	9, // 13: coloc.PaymentService.RejectPayment:output_type -> coloc.Payment
	8, // 14: coloc.PaymentService.CancelPayment:output_type -> coloc.CancelPaymentResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	file_payment_proto_msgTypes[0].OneofWrappers = []any{}
	file_payment_proto_msgTypes[2].OneofWrappers = []any{}
	file_payment_proto_msgTypes[5].OneofWrappers = []any{}
	file_payment_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		EnumInfos:         file_payment_proto_enumTypes,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
