// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Nom             *string                `protobuf:"bytes,1,opt,name=nom,proto3,oneof" json:"nom,omitempty"`
	Prenom          *string                `protobuf:"bytes,2,opt,name=prenom,proto3,oneof" json:"prenom,omitempty"`
	Telephone       *string                `protobuf:"bytes,3,opt,name=telephone,proto3,oneof" json:"telephone,omitempty"`
	AvatarUrl       *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	CurrentPassword *string                `protobuf:"bytes,5,opt,name=current_password,json=currentPassword,proto3,oneof" json:"current_password,omitempty"`
	NewPassword     *string                `protobuf:"bytes,6,opt,name=new_password,json=newPassword,proto3,oneof" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetNom() string {
	if x != nil && x.Nom != nil {
		return *x.Nom
	}
	return ""
}

func (x *UpdateUserRequest) GetPrenom() string {
	if x != nil && x.Prenom != nil {
		return *x.Prenom
	}
	return ""
}

func (x *UpdateUserRequest) GetTelephone() string {
	if x != nil && x.Telephone != nil {
		return *x.Telephone
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetCurrentPassword() string {
	if x != nil && x.CurrentPassword != nil {
		return *x.CurrentPassword
	}
	return ""
}

func (x *UpdateUserRequest) GetNewPassword() string {
	if x != nil && x.NewPassword != nil {
		return *x.NewPassword
	}
	return ""
}

type DeleteCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrentUserRequest) Reset() {
	*x = DeleteCurrentUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrentUserRequest) ProtoMessage() {}

func (x *DeleteCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nom           string                 `protobuf:"bytes,3,opt,name=nom,proto3" json:"nom,omitempty"`
	Prenom        string                 `protobuf:"bytes,4,opt,name=prenom,proto3" json:"prenom,omitempty"`
	Telephone     *string                `protobuf:"bytes,5,opt,name=telephone,proto3,oneof" json:"telephone,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // French formatted datetime
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // French formatted datetime
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetNom() string {
	if x != nil {
		return x.Nom
	}
	return ""
}

func (x *User) GetPrenom() string {
	if x != nil {
		return x.Prenom
	}
	return ""
}

func (x *User) GetTelephone() string {
	if x != nil && x.Telephone != nil {
		return *x.Telephone
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05coloc\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n" +
	"\x15GetCurrentUserRequest\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbc\x02\n" +
	"\x11UpdateUserRequest\x12\x15\n" +
	"\x03nom\x18\x01 \x01(\tH\x00R\x03nom\x88\x01\x01\x12\x1b\n" +
	"\x06prenom\x18\x02 \x01(\tH\x01R\x06prenom\x88\x01\x01\x12!\n" +
	"\ttelephone\x18\x03 \x01(\tH\x02R\ttelephone\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x03R\tavatarUrl\x88\x01\x01\x12.\n" +
	"\x10current_password\x18\x05 \x01(\tH\x04R\x0fcurrentPassword\x88\x01\x01\x12&\n" +
	"\fnew_password\x18\x06 \x01(\tH\x05R\vnewPassword\x88\x01\x01B\x06\n" +
	"\x04_nomB\t\n" +
	"\a_prenomB\f\n" +
	"\n" +
	"_telephoneB\r\n" +
	"\v_avatar_urlB\x13\n" +
	"\x11_current_passwordB\x0f\n" +
	"\r_new_password\"\x1a\n" +
	"\x18DeleteCurrentUserRequest\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x95\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x10\n" +
	"\x03nom\x18\x03 \x01(\tR\x03nom\x12\x16\n" +
	"\x06prenom\x18\x04 \x01(\tR\x06prenom\x12!\n" +
	"\ttelephone\x18\x05 \x01(\tH\x00R\ttelephone\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tH\x01R\tavatarUrl\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAtB\f\n" +
	"\n" +
	"_telephoneB\r\n" +
	"\v_avatar_url2\xe7\x02\n" +
	"\vUserService\x12R\n" +
	"\x0eGetCurrentUser\x12\x1c.coloc.GetCurrentUserRequest\x1a\v.coloc.User\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/users/me\x12T\n" +
	"\x11UpdateCurrentUser\x12\x18.coloc.UpdateUserRequest\x1a\v.coloc.User\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/api/users/me\x12f\n" +
	"\x11DeleteCurrentUser\x12\x1f.coloc.DeleteCurrentUserRequest\x1a\x19.coloc.DeleteUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/api/users/me\x12F\n" +
	"\aGetUser\x12\x15.coloc.GetUserRequest\x1a\v.coloc.User\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/users/{id}B,Z*github.com/vblanchet22/back_coloc/proto/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_proto_goTypes = []any{
	(*GetCurrentUserRequest)(nil),    // 0: coloc.GetCurrentUserRequest
	(*GetUserRequest)(nil),           // 1: coloc.GetUserRequest
	(*UpdateUserRequest)(nil),        // 2: coloc.UpdateUserRequest
	(*DeleteCurrentUserRequest)(nil), // 3: coloc.DeleteCurrentUserRequest
	(*DeleteUserResponse)(nil),       // 4: coloc.DeleteUserResponse
	(*User)(nil),                     // 5: coloc.User
}
var file_user_proto_depIdxs = []int32{
	0, // 0: coloc.UserService.GetCurrentUser:input_type -> coloc.GetCurrentUserRequest
	2, // 1: coloc.UserService.UpdateCurrentUser:input_type -> coloc.UpdateUserRequest
	3, // 2: coloc.UserService.DeleteCurrentUser:input_type -> coloc.DeleteCurrentUserRequest
	1, // 3: coloc.UserService.GetUser:input_type -> coloc.GetUserRequest
	5, // 4: coloc.UserService.GetCurrentUser:output_type -> coloc.User
	5, // 5: coloc.UserService.UpdateCurrentUser:output_type -> coloc.User
	4, // 6: coloc.UserService.DeleteCurrentUser:output_type -> coloc.DeleteUserResponse
	5, // 7: coloc.UserService.GetUser:output_type -> coloc.User
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[2].OneofWrappers = []any{}
	file_user_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
